### ISSUE TITLE
Error marks are shown in Che editor while IDE is resolving dependencies (no "progress information" available)

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#9581]
### Description
Related openshift.io issue - https://github.com/openshiftio/openshift.io/issues/3336

1- The "progress information" is not displayed in the status bar when ide is resolving dependencies
2- If resolving the dependencies is going to take long time - should we really display errors?

### Reproduction Steps
- start latest che on minishift
- create workspace based on `vert.x` stack and add `vertx-http-booster` [1]  project
- once workspace is started open any java file
- ERROR: there is a bunch of error markers in the editor which are disappeared after some time:
![image](https://user-images.githubusercontent.com/1461122/39511563-22e59456-4dee-11e8-8404-09852f416b40.png)

ERROR: The "progress information" is not displayed in the status bar

If resolving the dependencies is going to take long time - should we really display errors?

[1] https://github.com/openshiftio-vertx-boosters/vertx-http-booster
**OS and version:**  
minishift v1.9.0

**Comment by ScrewTSW** [comment]
@ibuziuk do the errors disappear once you do build?

**Comment by ibuziuk** [comment]
@ScrewTSW no

**Comment by ibuziuk** [comment]
have reworded the issue a bit with a focus on no "progress information" during indexing / resolving deps.
The original osio issue https://github.com/openshiftio/openshift.io/issues/3336 is related to the fact that pre-build deps on image level are not the same that are used in up-to-date quickstart - https://github.com/openshiftio/openshift.io/issues/3336#issuecomment-385926603

**Comment by artaleks9** [comment]
Still actual for ver. 6.6.0

**Comment by vparfonov** [comment]
will be fixed with switching to the jdt.ls
