### ISSUE TITLE
Adding custom plugin to Che

### ISSUE THREAD

**Issue by kvandenhoute** [eclipse-che/che#9587]
### Description
I'm trying to add my custom made plugin to che. I added the necessary dependencies to pom.xml and built the project. However when launching, I can't find it. Looking a lot like this problem https://github.com/eclipse/che/issues/2330.

### Reproduction Steps
These are the dependencies
assembly-ide-war dependencies
```
 <dependencies>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.che.core</groupId>
            <artifactId>che-ide-core</artifactId>
            <type>gwt-lib</type>
        </dependency>
        <dependency>
            <groupId>org.eclipse.che.sample</groupId>
            <artifactId>plugin-wizard-ide</artifactId>
            <type>gwt-lib</type>
        </dependency>
        <dependency>
            <groupId>org.eclipse.che</groupId>
            <artifactId>assembly-ide-war</artifactId>
            <type>war</type>
        </dependency>
    </dependencies>
```

assembly-main dependencies
```
    <dependencies>
        <dependency>
            <groupId>org.eclipse.che.sample</groupId>
            <artifactId>assembly-ide-war</artifactId>
            <type>war</type>
        </dependency>
        <dependency>
            <groupId>org.eclipse.che.sample</groupId>
            <artifactId>assembly-wsagent-server</artifactId>
            <type>tar.gz</type>
        </dependency>
    </dependencies>
```

assemblye-wsagent-server dependencies
```
    <dependencies>
        <dependency>
            <groupId>org.eclipse.che.sample</groupId>
            <artifactId>assembly-wsagent-war</artifactId>
            <type>war</type>
        </dependency>
    </dependencies>

```

assembly-wsagent-war dependencies
```
    <dependencies>
        <dependency>
            <groupId>org.eclipse.che.core</groupId>
            <artifactId>che-wsagent-core</artifactId>
            <type>war</type>
        </dependency>
        <dependency>
            <groupId>org.eclipse.che.sample</groupId>
            <artifactId>plugin-wizard-server</artifactId>
        </dependency>
    </dependencies>
```

I then built che with
The assembly & plugins folder are in /projects/JEWizard
```
cd /projects/JEWizard
mvn clean install

```

And afterwards ran it with
sudo docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /path/to/data:/data -v /path/to/build/eclipse-che-6.5.0-SNAPSHOT/:/assembly eclipse/che start

Eclipse che runs perfectly but there is no sign of my plugin.
However, I did some digging in the ROOT.war in the tomcat webapps folder where I found the ExtensionManager.class. After decompiling that class, I found that the extension is added.
```
        (this.extensions = new HashMap<String, Provider>()).put("org.eclipse.che.ide.workspace.activity.ActivityTrackingExtension", activitytrackingextension);
        this.extensions.put("org.eclipse.che.ide.editor.orion.client.OrionEditorExtension", orioneditorextension);
        this.extensions.put("org.eclipse.che.ide.factory.FactoryExtension", factoryextension);
        this.extensions.put("org.eclipse.che.sample.ide.SampleWizardExtension", samplewizardextension);

```

The question now is, is the plugin not added correctly or is it added correctly but badly injected?
In both cases, any idea on how to fix this?

**Comment by eivantsov** [comment]
@Farleon is this a custom plugin or a sample one https://github.com/che-samples/che-plugin-wizard?

**Comment by Farleon** [comment]
@eivantsov Any idea what I do wrong?

**Comment by cenkce** [comment]
I got similar issue. I built che-samples/che-plugin-wizard, che-plugin-menu, che-plugin-embedjs then I ran sudo docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /path/to/data:/data -v /path/to/plugin/assembly:/assembly eclipse/che start 

But no plugin when I create a new workspace.

**Comment by eivantsov** [comment]
@cenkce each plugin is an assembly, so you can run just one at a time, unless you included all dependencies to these plugins in one Che assembly.

I have taken a look at CI tests with selenium tests for a sample plugin and saw no failures.

Can you run the following and share the output?

```
docker exec -ti che bash
ps ax
```

**Comment by cenkce** [comment]
```
1 root       0:00 {entrypoint.sh} /bin/bash /entrypoint.sh
 28 root       0:00 {entrypoint.sh} /bin/bash /entrypoint.sh
 29 root       0:35 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Djava.util.lo
137 root       0:00 bash
143 root       0:00 ps ax
```

**Comment by cenkce** [comment]
I have been using che-6.4.1.

**Comment by eivantsov** [comment]
I have just given a try with this one - https://github.com/che-samples/che-ide-server-extension

```
git clone https://github.com/che-samples/che-ide-server-extension
cd che-ide-server-extension
git checkout 6.5.0
mvn clean install -DskipTests
docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v ~/Documents/cheplugin:/data -v $(pwd)/assembly/assembly-main/target/eclipse-che-6.5.0/eclipse-che-6.5.0:/assembly eclipse/che:6.5.0 start --fast
```
Start a workspace, right click to call context menu:

![image](https://user-images.githubusercontent.com/5337267/40157119-f6514fc0-59a5-11e8-89ca-dcc3c046d57b.png)

And clicking on it produces:

![image](https://user-images.githubusercontent.com/5337267/40157129-0403db4c-59a6-11e8-9051-1bcc1ac5675a.png)


And if we take a look at container processes, we can see that `che.home=/assembly` which means your custom built Che assembly (tomcat with custom artifacts) has started.
```
docker exec che ps ax
PID   USER     TIME   COMMAND
    1 root       0:00 {entrypoint.sh} /bin/bash /entrypoint.sh
   27 root       0:00 {entrypoint.sh} /bin/bash /entrypoint.sh
   28 root       0:36 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Djava.util.logging.config.file=/assembly/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m -Dche.docker.network=bridge -Dport.http=8080 -Dche.home=/assembly -Dche.logs.dir=/logs -Dche.logs.level=INFO -Djuli-logback.configurationFile=file:/assembly/tomcat/conf/tomcat-logger.xml -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dche.local.conf.dir=/assembly/tomcat/conf/ -classpath /assembly/tomcat/conf/:/usr/lib/jvm/java-1.8-openjdk/jre/lib/tools.jar:/assembly/tomcat/bin/bootstrap.jar:/assembly/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/assembly/tomcat -Dcatalina.home=/assembly/tomcat -Djava.io.tmpdir=/assembly/tomcat/temp org.apache.catalina.startup.Bootstrap start
  150 root       0:00 ps ax
```
Hope this helps

**Comment by cenkce** [comment]
Yes thank you

**Comment by cenkce** [comment]
What is the fastest way to develop, build a plugin and deploy to localhost.

**Comment by cenkce** [comment]
Do you plan to replace completely current Editor with Theia Editor?

**Comment by eivantsov** [comment]
Theia uses Monaco editor

**Comment by cenkce** [comment]
I mean with your current GWT based IDE

**Comment by eivantsov** [comment]
Current GWT IDE will keep using Orion

**Comment by cenkce** [comment]
Thank you so much.
