### ISSUE TITLE
MACHINE_TOKEN is not available in SSH

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#9588]
### Description
When using SSH to connect to a workspace, none of the CHE_ environment variables are available (for example CHE_API). Most importantly, `MACHINE_TOKEN` is not available which means that via SSH we can't run any commands/tools we have that communicate with the CHE_API.

`GIT_SSH` is available however and appears to be injected like so https://github.com/eclipse/che/blob/2c2bd6637c8169018e2b33397f9d738bbf82a0b1/agents/git-credentials/src/main/resources/installers/1.0.0/org.eclipse.che.git.script.sh#L57

### Reproduction Steps
SSH into a remote workspace, type `env`.

**OS and version:**    
Che 6.4.1

**Comment by eivantsov** [comment]
@davidwindell that's not Che specific problem

https://stackoverflow.com/questions/34630571/docker-env-variables-not-set-while-log-via-shell?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

As a workaround, I'd write all envs to /etc/environment on container start (in the entrypoint). Of course, you will need a custom stack for it.

**Comment by davidwindell** [comment]
Ah, of course, thank you so much @eivantsov, that's a great idea!

**Comment by davidwindell** [comment]
Perhaps there is an argument for adding to /etc/environment in the SSH agent launch script?

**Comment by davidwindell** [comment]
Closing as not relevant to Che 7 without SSH access
