### ISSUE TITLE
Unable to create project from wizard in new workspace

### ISSUE THREAD

**Issue by msoltow** [eclipse-che/che#959]
Che Version: Nightly build 4.1.0-RC1-SNAPSHOT
Revision: a21f016af1ad323
OS: Windows

Steps to reproduce error:
1. Start Che
2. Navigate to the dashboard and click "Projects"
3. Click the + icon in the upper right-hand corner
4. Select the following options to create a project and new workspace at the same time:
   1. Source: New from blank, template, or sample project
   2. Stack: Java CentOS
   3. Template: Wizard-driven
5. Click "Create Project"
6. Click "Open Project in IDE"
7. Select "Python Project" and click "Create"

Result: The "Create" button changes to a loading icon that just hangs.  Inspecting the Dev Console shows that a POST request was made to http://localhost:8080/ide/ext/project/workspacejv7cvewr2n58n63l and received a response of 409 - Path for new project should be defined.

However, if instead of creating the project and workspace at the same time I create the workspace by itself, open the workspace in the IDE, select "Create Project" from the "Workspace" menu, and then try to build a Python project, then everything works perfectly.

**Comment by ddementieva** [comment]
Thanks for reporting a bug. Team is working on a fix.

**Comment by ghost** [comment]
Fixed in master - https://github.com/eclipse/che/commit/efaca3a853538329ba080a2862a46f2f04c0aad6
