### ISSUE TITLE
Address Selenium Test Merge Blockers

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9591]
Epic for addressing issues found in selenium tests with jdt.ls.

- [x] https://github.com/eclipse/che/issues/10431
- [x] https://github.com/eclipse/che/issues/10115
- [x] https://github.com/eclipse/che/issues/10425
- [x] https://github.com/eclipse/che/issues/10112
- [x] https://github.com/eclipse/che/issues/10095 
- [x] https://github.com/eclipse/che/issues/10094
- [x] https://github.com/eclipse/che/issues/10034
- [x] https://github.com/eclipse/che/issues/10451
- [x] https://github.com/eclipse/che/issues/10466

**Comment by tsmaeder** [comment]
Package | Tests | Errors | Failures | Skipped | Success Rate | Time
-- | -- | -- | -- | -- | -- | --
org.eclipse.che.selenium.preferences | 7 | 0 | 2 | 0 | 71.429% | 222.404
org.eclipse.che.selenium.refactor.types | 17 | 0 | 1 | 0 | 94.118% | 328.927
org.eclipse.che.selenium.refactor.methods | 30 | 0 | 2 | 7 | 70% | 513.79
org.eclipse.che.selenium.dashboard | 25 | 0 | 1 | 0 | 96% | 277.458
org.eclipse.che.selenium.debugger | 45 | 0 | 3 | 5 | 82.222% | 537.671
org.eclipse.che.selenium.plainjava | 5 | 0 | 4 | 1 | 0% | 38.358
org.eclipse.che.selenium.dashboard.workspaces.details | 9 | 0 | 4 | 0 | 55.556% | 154.271
org.eclipse.che.selenium.testrunner | 6 | 0 | 0 | 0 | 100% | 144.4
org.eclipse.che.selenium.gwt | 1 | 0 | 0 | 0 | 100% | 143.316
org.eclipse.che.selenium.intelligencecommand | 17 | 0 | 5 | 9 | 17.647% | 420.408
org.eclipse.che.selenium.refactor.move | 13 | 0 | 4 | 0 | 69.231% | 443.595
org.eclipse.che.selenium.refactor.preview | 2 | 0 | 0 | 0 | 100% | 6.974
org.eclipse.che.selenium.workspaces | 9 | 0 | 3 | 0 | 66.667% | 324.146
org.eclipse.che.selenium.git | 61 | 0 | 4 | 15 | 68.852% | 1,619.099
org.eclipse.che.selenium.swagger | 1 | 0 | 0 | 0 | 100% | 2.23
org.eclipse.che.selenium.editor.autocomplete | 18 | 0 | 12 | 0 | 33.333% | 654.818
org.eclipse.che.selenium.languageserver | 10 | 0 | 5 | 5 | 0% | 147.695
org.eclipse.che.selenium.projectexplorer | 102 | 0 | 7 | 0 | 93.137% | 1,913.181
org.eclipse.che.selenium.refactor.packages | 16 | 0 | 3 | 1 | 75% | 393.636
org.eclipse.che.selenium.projectexplorer.dependencies | 2 | 0 | 1 | 0 | 50% | 103.235
org.eclipse.che.selenium.stack | 3 | 0 | 1 | 0 | 66.667% | 237.151
org.eclipse.che.selenium.dashboard.workspaces | 15 | 0 | 7 | 4 | 26.667% | 108.002
org.eclipse.che.selenium.refactor.fields | 42 | 0 | 4 | 0 | 90.476% | 834.546
org.eclipse.che.selenium.editor | 22 | 0 | 1 | 8 | 59.091% | 425.506
org.eclipse.che.selenium.filewatcher | 11 | 0 | 1 | 0 | 90.909% | 371.422
org.eclipse.che.selenium.miscellaneous | 57 | 0 | 5 | 0 | 91.228% | 1,298.121
org.eclipse.che.selenium.factory | 13 | 0 | 2 | 0 | 84.615% | 668.254
org.eclipse.che.selenium.mavenplugin | 5 | 0 | 3 | 2 | 0% | 244.522
org.eclipse.che.selenium.assistant | 10 | 0 | 2 | 0 | 80% | 100.338
org.eclipse.che.selenium.refactor.parameters | 19 | 0 | 1 | 0 | 94.737% | 325.915
org.eclipse.che.selenium.opendeclaration | 10 | 0 | 0 | 0 | 100% | 277.217

**Comment by tolusha** [comment]
https://github.com/eclipse/che/pull/10418
https://github.com/eclipse/che-ls-jdt/pull/59
