### ISSUE TITLE
UX bug when editing html documents

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#9593]
### Description
I've ran into this bug when I was playing around with Springboot HTTP Booster stack.
I wanted to edit some elements on the page and when I started editing code, I've noticed the weird way the elements get highlighted.

Tested on upstream as well, issue still present.

### Reproduction Steps
* Create new springboot-http-booster project
* Open project files -> resources -> index.html
* Click inside any class

**OS and version:**    
Fedora 27
RH-Che + Eclipse Che 6.4.1

![screenshot from 2018-05-03 08-57-44](https://user-images.githubusercontent.com/16451875/39563960-747e95e6-4eb2-11e8-9b9b-be1d74039fee.png)

**Comment by danidoedel** [comment]
Duplicates #8867

**Comment by ScrewTSW** [comment]
@danidoedel correct - closing
