### ISSUE TITLE
Introduce the plugin API for terminal

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9595]
The new plugin model should contain API for creating and accessing terminal in Theia. The task includes following items to be done:
- [x] define the API of the terminal operations
- [x]  document the API
- [x]  develop the defined API
- [x]  test it on the sample plugin

**Comment by AndrienkoAleksandr** [comment]
awaiting merge https://github.com/theia-ide/theia/pull/2001 . And pull request https://github.com/theia-demo-plugins/wiptheia/pull/24 should be moved to the Theia repo.

**Comment by AndrienkoAleksandr** [comment]
Pull request https://github.com/theia-demo-plugins/wiptheia/pull/24 was moved to the theia repo: https://github.com/theia-ide/theia/pull/2187

**Comment by AndrienkoAleksandr** [comment]
Upstream pull request merged https://github.com/theia-ide/theia/pull/2187. Close issue.
