### ISSUE TITLE
dashboard in docker

### ISSUE THREAD

**Issue by dklesev** [eclipse-che/che#96]
_dashboard_ is not available (che in docker).
get 404.

![](http://i.imgur.com/bqI8oO2.png)

**Comment by TylerJewell** [comment]
Hi Dmitrij:

It looks like for some reason the latest builds that include the dashboard
have not been packaged into the docker image.

Could you try building from source:
git clone http://github.com/codenvy/che
mvn clean install

This should let you have access to the dashboard, which was just added.

We'll get the docker image updated.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by dklesev** [comment]
building from source returns error code 137.
[end of log](http://pastebin.com/CK5r6RtP)

``` bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

$ mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/share/maven3
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-25-generic", arch: "amd64", family: "unix"
```

**Comment by TylerJewell** [comment]
Would you go into the assembly-sdk directory and attempt a mvn clean
install there?  This will build the assembly from the hosted libraries.

The other error is unusual and needs investigation.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by dklesev** [comment]
ok it works. thx

**Comment by dklesev** [comment]
ok it works. thx
so there is now another issue: (trying to install plug-ins (from dashboard))

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.869 s
[INFO] Finished at: 2015-11-15T03:34:37+01:00
[INFO] Final Memory: 26M/62M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (distribution-management-used) on project assembly-sdk-war: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Build of che assembly failed
```

with `git clone & mvn clean install`:

[error log](http://pastebin.com/Eu7yZa8Z)

**Comment by vparfonov** [comment]
Hi can you provide full log ?

**Comment by dklesev** [comment]
trying to install plug-ins via web gui:

[web gui err log](http://pastebin.com/wPQYuS3K)

`git clone & mvn clean install` works (for plugins - like in the docs). I had a memory issue.

**Comment by ghost** [comment]
Can you try it with a non-snapshot, say https://github.com/codenvy/che/releases/tag/3.13.4.3

**Comment by Metal-Mighty** [comment]
Hi, I'm having the same issues as asdklesev. I tried the non-snapshot you just linked but it fails to build correctly. Here's the failing part:

```
//DTD SVG 1.1//EN, http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd, jar:file:/root/.m2/repository/org/eclipse/che/core/che-core-ide-app/3.13.4.3/che-core-ide-app-3.13.4.3.jar!/org/eclipse/che/ide/menu/submenu.svg)
[INFO]    Compiling 4 permutations
[INFO]       Compiling permutation 0...
[INFO]       Process output
[INFO]          Compiling
[INFO]             Compiling permutation 1...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Che :: Parent ...................................... SUCCESS [ 27.140 s]
[INFO] Che :: Plugin Tools ................................ SUCCESS [  0.656 s]
[INFO] Che :: Plugin Tools :: API Plugin .................. SUCCESS [02:14 min]
[INFO] Che :: Examples .................................... SUCCESS [ 11.777 s]
[INFO] Che :: Examples :: Action .......................... SUCCESS [ 53.653 s]
[INFO] Che :: Examples :: Project Type .................... SUCCESS [ 33.146 s]
[INFO] Che :: Examples :: Service ......................... SUCCESS [ 25.682 s]
[INFO] Che :: Examples :: Theme ........................... SUCCESS [ 37.063 s]
[INFO] Che :: Examples :: Multi Extension ................. SUCCESS [  0.518 s]
[INFO] Che :: Examples :: Multi Extension :: Action ....... SUCCESS [ 32.327 s]
[INFO] Che :: Examples :: Multi Extension :: ProjectType .. SUCCESS [ 29.639 s]
[INFO] Che :: Examples :: Multi Extension :: Service ...... SUCCESS [ 26.335 s]
[INFO] Che :: Examples :: Multi Extension :: Theme ........ SUCCESS [ 30.157 s]
[INFO] Che :: Examples :: Multi Extension :: Assembly ..... SUCCESS [  3.283 s]
[INFO] Che :: Archetypes .................................. SUCCESS [  1.118 s]
[INFO] Che :: Archetypes :: Client Extension .............. SUCCESS [ 15.561 s]
[INFO] Che :: Archetypes :: Server Extension .............. SUCCESS [  0.595 s]
[INFO] Che :: Archetypes :: Project Type .................. SUCCESS [  0.855 s]
[INFO] Che :: Archetypes :: Multi module Extension ........ SUCCESS [  1.172 s]
[INFO] Che :: Admin war ................................... SUCCESS [ 36.270 s]
[INFO] Che :: Compiling GWT Application ................... FAILURE [22:57 min]
[INFO] Che :: Assemblies Tomcat ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31:33 min
[INFO] Finished at: 2015-12-05T05:12:14+01:00
[INFO] Final Memory: 146M/472M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.7.0:compile (default) on project assembly-sdk-war
```

... Followed by a very large command and `[ERROR] ]] failed with status 137`

**Comment by ghost** [comment]
It  looks like a memory issue. How much RAM do you have?

You can give it a try with the following argument -Dgwt.compiler.localWorkers=1

**Comment by Metal-Mighty** [comment]
I only have 4GB so it may be the issue yes. When using the argument I get a OutOfMemoryError later in the build process.

```
[INFO]    Compiling 4 permutations
[INFO]       Compiling permutation 0...
[INFO]       Compiling permutation 1...
[INFO]       Compiling permutation 2...
[INFO]       Compiling permutation 3...
[INFO]    Compile of permutations succeeded
[INFO]    Compilation succeeded -- 1529.968s
[INFO] Linking into /opt/che-3.13.4.3/assembly-sdk-war/target/assembly-sdk-war-3.13.4.3/_app
[INFO]    Link succeeded
[INFO]    Linking succeeded -- 12.669s
[INFO] Compiling module org.eclipse.che.ide.ext.java.JavaParserWorker
[INFO]    Ignored 24 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[ERROR] Exception in thread "main" java.lang.OutOfMemoryError: unable to create new native thread
[ERROR]         at java.lang.Thread.start0(Native Method)
[ERROR]         at java.lang.Thread.start(Thread.java:714)
[ERROR]         at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:335)
[ERROR]         at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildGeneratedTypes(CompilationStateBuilder.java:649)
[ERROR]         at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.addGeneratedTypes(CompilationStateBuilder.java:242)
[ERROR]         at com.google.gwt.dev.javac.CompilationState.addGeneratedCompilationUnits(CompilationState.java:125)
[ERROR]         at com.google.gwt.dev.javac.StandardGeneratorContext.finish(StandardGeneratorContext.java:557)
[ERROR]         at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.buildEntryMethodHolder(JavaToJavaScriptCompiler.java:1019)
[ERROR]         at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1035)
[ERROR]         at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$Precompiler.precompile(JavaToJavaScriptCompiler.java:954)
[ERROR]         at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.precompile(MonolithicJavaToJavaScriptCompiler.java:303)
[ERROR]         at com.google.gwt.dev.jjs.JavaScriptCompiler.precompile(JavaScriptCompiler.java:38)
[ERROR]         at com.google.gwt.dev.Precompile.precompile(Precompile.java:286)
[ERROR]         at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
[ERROR]         at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
[ERROR]         at com.google.gwt.dev.Compiler.run(Compiler.java:206)
[ERROR]         at com.google.gwt.dev.Compiler.run(Compiler.java:158)
[ERROR]         at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
[ERROR]         at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[ERROR]         at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[ERROR]         at com.google.gwt.dev.Compiler.main(Compiler.java:127)
```

**Comment by ghost** [comment]
4GB may be insufficient to for a GWT compilation

**Comment by rnavagamuwa** [comment]
I'm also getting this issue when I'm trying to add an extension. I have 8GB ram

**Comment by rnavagamuwa** [comment]
This is the error I'm getting and I'm getting this only when I add my extension. 
`[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Che IDE :: Parent .................................. SUCCESS [  4.013 s]
[INFO] Che Machine Plugins :: Packaging ................... SUCCESS [ 25.006 s]
[INFO] Che Assembly Machine Plugins :: Server ............. SUCCESS [  2.460 s]
[INFO] Che IDE :: Compiling GWT Application ............... FAILURE [  0.643 s]
[INFO] Che IDE :: Assemblies Tomcat ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 33.330 s
[INFO] Finished at: 2016-03-23T19:50:23+05:30
[INFO] Final Memory: 73M/1288M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (distribution-management-used) on project assembly-ide-war: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
`

**Comment by rnavagamuwa** [comment]
I'm getting this error only when I add my extension

> [INFO] Reactor Summary:
> [INFO] 
> [INFO] Che IDE :: Parent .................................. SUCCESS [  4.013 s]
> [INFO] Che Machine Plugins :: Packaging ................... SUCCESS [ 25.006 s]
> [INFO] Che Assembly Machine Plugins :: Server ............. SUCCESS [  2.460 s]
> [INFO] Che IDE :: Compiling GWT Application ............... FAILURE [  0.643 s]
> [INFO] Che IDE :: Assemblies Tomcat ....................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 33.330 s
> [INFO] Finished at: 2016-03-23T19:50:23+05:30
> [INFO] Final Memory: 73M/1288M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (distribution-management-used) on project assembly-ide-war: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]

**Comment by benoitf** [comment]
there is an enforrcer rule that has failed. You should paste the log before the summary it will contain the real error

**Comment by benoitf** [comment]
also I think your issue is a different issue than the attached one (not linked to memory)

**Comment by rnavagamuwa** [comment]
Yes, problem is with the enforcer plugin. It's not related to this one.

**Comment by benoitf** [comment]
so you should look at the enforcer rule that is not valid with your change

**Comment by rnavagamuwa** [comment]
Yeah I have found the problem. It works fine now. Thanks for pointing out :+1:

**Comment by ghost** [comment]
Closing the issue, as it seems the problem is fixed now.
