### ISSUE TITLE
Prevent execution of QA CI jobs if che-server image wasn't updated on Docker Hub

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9610]
### Description
We have regularly situation when [Eclipse Che QA CI jobs](https://ci.codenvycorp.com/view/qa) execute selenium tests against outdated Eclipse Che version because [che-server image on Docker Hub](https://hub.docker.com/r/eclipse/che-server) hasn't been updated by [appropriate CI job](https://ci.codenvycorp.com/view/nightly-builds/job/all-che-docker-images-nightly/). For example, [builds on May 2nd](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-master-ocp/231/) were redundant because of [fail of che-server image build](https://ci.codenvycorp.com/view/nightly-builds/job/all-che-docker-images-nightly/541/).

As a solution, we can add dependency on [build che-server image CI job](https://ci.codenvycorp.com/view/nightly-builds/job/all-che-docker-images-nightly/) to the each [Eclipse Che QA CI jobs](https://ci.codenvycorp.com/view/qa) - build those QA jobs just after build of che-server image CI job has been finished successfully, instead of building them by schedule. 
It also prevents too early execution of Eclipse Che QA jobs if build of che-server image hasn't been finished in time.

**Comment by riuvshin** [comment]
I;ve replaced scheduler trigger with dependency for all nightly qa jobs with quiet period = 10m.
