### ISSUE TITLE
Installation without Docker

### ISSUE THREAD

**Issue by vanzhiganov** [eclipse-che/che#9613]
How I can Install Che IDE without Docker?

**Comment by skabashnyuk** [comment]
You have two alternatives OpenShift https://www.eclipse.org/che/docs/openshift-single-user.html and Kubernetes https://www.eclipse.org/che/docs/kubernetes-single-user.html

**Comment by vanzhiganov** [comment]
This is not an answer, because in my case any layers (like docker, kibe and osh) is big overhead for my working system environment.
