### ISSUE TITLE
Add support for multiple plugins in Theia hosted mode

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#9618]
### Description
We should support multiple plugins in hosted mode to be able to test plugins interactions.
For example, the hosted environment uses the plugin from workspace and hooks the debugger.

**Comment by benoitf** [comment]
maybe it's duplicating https://github.com/eclipse/che/issues/9476
AFAIK this issue is more to be able to select/define the multiple plugins that you need on hosted server (from a client side perspective), not to run multiple which is possible with the linked issue.
