### ISSUE TITLE
Different behaviour observed when a build command is executed from terminal vs che.command

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#9621]
### Description
There is a difference between the execution of a command from a Che command and executing it from the terminal.

See: https://github.com/openshiftio/openshift.io/issues/3463

See animated video:    
![terminal-command](https://user-images.githubusercontent.com/1636769/39638327-32928f4c-4fc6-11e8-86fd-7e562d860763.gif)

**Diagnostics:** 
6.4.1

**Comment by skabashnyuk** [comment]
related to https://github.com/eclipse/che/issues/9588

**Comment by slemeur** [comment]
@skabashnyuk Could you explain how this issue is related to #9588 and if you have a resolution/workaround proposal?

**Comment by skabashnyuk** [comment]
Build command and terminal uses different backend to actually execute commands. I assume they have different behavior how they work with ```tty``` and how they setup environment (.bashrc , .profile etc).  I belive that this is a source of the problem

**Comment by slemeur** [comment]
Any suggestion on how we could workaround that? the downstream issue openshiftio/openshift.io#3463 is quite critical at this moment.

**Comment by skabashnyuk** [comment]
Commented here https://github.com/openshiftio/openshift.io/issues/3463#issuecomment-386791795

**Comment by eivantsov** [comment]
@slemeur what are your expectations for upstream Che?

**Comment by artaleks9** [comment]
Still actual for ver.6.6.0

**Comment by slemeur** [comment]
A user, could be quite surprised by this behaviour and not understand that particular scenario could be surprising. 

We should probably start by having docs to provide clarification on this. 

Then to resolve this issue, should/could we have a way for the user to see and configure the environment variables for the commands?

**Comment by eivantsov** [comment]
We should have reasonable JAVA_OPTS and MAVEN_OPTS and should not have anything in ~/.bashrc in the image https://github.com/eclipse/che-dockerfiles/blob/master/recipes/centos_jdk8/Dockerfile#L34

**Comment by slemeur** [comment]
@eivantsov : It's a fair point for the stacks that are packaged by default. But what if the user is defining his own stack? He should be aware (in the docs) that the environment variables used for command execution could be different from the ones used in the terminal, no?

Have we got a way for the user to see & configure the environment variables used in the context of command execution?

**Comment by eivantsov** [comment]
@slemeur well, you can export any env before executing a command

**Comment by eivantsov** [comment]
I will review Dockerfiles to make sure there are no exports in ~/.bashrc. This way, commands in terminal and commands from command widget will produce identical output

**Comment by slemeur** [comment]
Thanks @eivantsov !

**Comment by eivantsov** [comment]
So, PR merged. It'll take some time for CI to rebuild and push images. ENVs can be declared:

1. In ws config, per machine
2. In an OpenShift/K8S yaml (recipe)
3. In am image definition (Dockerfile)
4. In a command syntax, preceding the command - export FOO=BAR

**Comment by eivantsov** [comment]
Fixed  and checked on che.openshift.io. None of the Dockerfiles explicitly add any exports to ` ~/.bashrc`

Terminal:

![image](https://user-images.githubusercontent.com/5337267/43504664-f794a1d6-956c-11e8-9667-320a027623b4.png)

Command:

![image](https://user-images.githubusercontent.com/5337267/43504685-0ade0b24-956d-11e8-846f-6758297c8ba0.png)
