### ISSUE TITLE
Creating custom workspace

### ISSUE THREAD

**Issue by kostiamol** [eclipse-che/che#9632]
I'd like to use a Go stack with go version 1.10.02. As I see, I should create my own stack. Also, I'd like to add my own sample for running it on the stack. Do I need to write a plugin for that? Is there any way to somehow automate the process of using all my custom stuff by other users?

**Comment by eivantsov** [comment]
@kostiamol you don't need a plugin.

You can create own stack from a Dockerfile, Docker image or Composefile (if you are on Docker of course). As to samples, if you take a look at `/instance/data/templates` in the local storage directory for Che. There's a json there with default samples. You can create your own json to put near this one. Take a look at tags in stacks and samples, this is how dashboard filters samples for chosen stacks.

**Comment by kostiamol** [comment]
@eivantsov Hmm... My templates folder is empty.

**Comment by eivantsov** [comment]
`instance/data/templates` not `instance/templates`

**Comment by kostiamol** [comment]
![screenshot from 2018-05-07 14-11-30](https://user-images.githubusercontent.com/5477699/39701225-a843fba4-5200-11e8-918d-caf43e1ad630.png)

**Comment by kostiamol** [comment]
@eivantsov I found all the samples.json files on my machine. 

![screenshot from 2018-05-16 12-36-47](https://user-images.githubusercontent.com/5477699/40112520-7e95ed8c-5906-11e8-848c-4d71a7a158f1.png)

I changed the contents of data/templates/samples.json but che didn't show the changes. I even deleted that file but che showed all the standard samples as if nothing had happened.

**Comment by davidwindell** [comment]
@kostiamol you need to call your customer samples.json something other than `samples.json`, i.e. `custom-samples.json`.

**Comment by kostiamol** [comment]
@davidfestal Thanks. It turned out, that I had forgotten to disable cache in my browser. As a result, I didn't see any changes in samples.

**Comment by kostiamol** [comment]
@davidfestal And cal I also create a stack and workspace from a json file?

**Comment by kostiamol** [comment]
@davidwindell And how could I define a stack? Where should I put `stacks.json file`?

**Comment by eivantsov** [comment]
@kostiamol you cat add a stack using REST API. So to /swagger to look at available methods

**Comment by kostiamol** [comment]
@eivantsov Thanks, works like a charm.

**Comment by eivantsov** [comment]
@kostiamol so what you say is that there's no PVC `che-data-claim`?

**Comment by kostiamol** [comment]
@eivantsov It seems to be so, because `kubectl get pvc -n che-ns` doesn't show it. Maybe because of this?
```
{{- if not .Values.global.multiuser }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: che
  name: che-data-volume
```
[Commit message: Disable che-data pvc creation for musltiuser che deployment](https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/pvc.yaml)

**Comment by eivantsov** [comment]
Probably yes

**Comment by kostiamol** [comment]
@eivantsov So, how could add my samples?

**Comment by eivantsov** [comment]
@kostiamol I'd remove `{{- if not .Values.global.multiuser }}` and redeploy

**Comment by kostiamol** [comment]
I commented the line but nothing changed. @akorneta Could you help with that?

**Comment by eivantsov** [comment]
@kostiamol did you comment this one too? https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/pvc.yaml#L21

It is weird that a Helm never applied the template.

**Comment by kostiamol** [comment]
@eivantsov It still doesn't work. Ok, there isn't any pvc for che, but where then the sample.json is stored?

**Comment by eivantsov** [comment]
@kostiamol if there's no pvc, unfortunately, there's no way to provide own samples

**Comment by eivantsov** [comment]
@kostiamol what you need to do is to remove (not comment) those ifs in pvc.yaml and deployment.yaml (multiple occurrences). Just search for `che-data-volume` in helm directory.

**Comment by kostiamol** [comment]
@eivantsov Yeeeah, it works. But why it didn't work when I only commented the lines without deleting them? And second question: I've copied using `kubectl cp` my `custom-samples.json` to both `/data/templates` and `/home/user/eclipse-che/templates `but che doesn't show it. Should I move the copy operation to the configs or what?

**Comment by eivantsov** [comment]
Can you confirm this file is there when you restart Che?

**Comment by kostiamol** [comment]
@eivantsov Now it works. I copied my file to` /data/templates `and deleted the che pod (according to the deployment it was recreated automatically).

**Comment by kostiamol** [comment]
@eivantsov It's not good to execute manually `kubectl cp custom-samples.json che-8467596d54-7c2hg:/data/templates` each time after deployment. Is there any way to do it automatically?

**Comment by eivantsov** [comment]
@kostiamol there's no automation other than building own custom Che assembly

**Comment by skabashnyuk** [comment]
@kostiamol can we close this issue or redefine again its scope?

**Comment by eivantsov** [comment]
I doubt stacks and samples will have the same meaning in Che 7.
