### ISSUE TITLE
[Kubernetes] CPU limits for workspaces

### ISSUE THREAD

**Issue by mjshashank** [eclipse-che/che#9638]
### Description

While in docker setup it is possible to set up CPU limits using environment variables for workspaces, is the same possible in a Kubernetes setup by setting CPU requests and limits?

**Comment by eivantsov** [comment]
@mjshashank as far as I know, there's no way to limit CPU on OpenShift/K8S

**Comment by mjshashank** [comment]
@eivantsov Since kuberenets supports [resource quotas](https://kubernetes.io/docs/concepts/policy/resource-quotas/), is it in the plan to set new Kubernetes Infra parameters for the same so that it is reflected in the pod configuration?

**Comment by eivantsov** [comment]
@l0rd @garagatyi are there any plans to introduce cpu caps?

**Comment by garagatyi** [comment]
I'm not aware of it
