### ISSUE TITLE
OpenShift/K8S: Log installer errors in wsmaster log

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9641]
At times, workspaces fail to start when an installer fails. Installer logs are streamed to machine tab in consoles panel in the IDE. However, in use cases when the IDE is not opened (or a page is refreshed) logs are unavailable and there are no clues why an installer fails.

So, having installer error logs in master will be extremely helpful in debugging issues and support.

**Comment by sleshchenko** [comment]
@eivantsov @skabashnyuk Should it be closed?

**Comment by eivantsov** [comment]
Yes.
