### ISSUE TITLE
Show dialog window to open Theia Hosted Instance in case browser blocks opening of a new tab

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#9644]
### Description
Hosted plugin manager for https://github.com/theia-demo-plugins/wiptheia doesn't start a plugin instance.  And styles of select path window should be more readable.
![selection_006](https://user-images.githubusercontent.com/6310786/39743792-c6b7a1d0-52aa-11e8-8e2f-abb48ebe442d.png)

### Reproduction Steps

1. Open wiptheia and select path a plugin instance.
![selection_007](https://user-images.githubusercontent.com/6310786/39743778-b8f8a116-52aa-11e8-8cbe-48307d174a4f.png)
2. Start instanse.
![selection_008](https://user-images.githubusercontent.com/6310786/39744866-4714046a-52ae-11e8-9e2b-6ee842c96da3.png)
3. Open a new page with the needed link. And there is no the checked plugin.
In the case of env HOSTED_PLUGIN all is OK.

**Comment by mmorhun** [comment]
So @olexii4 gives an idea to improve IDE behaviour in case popups is blocked. So we can add dialog with link to click to open a new tab with hosted instance.

**Comment by mmorhun** [comment]
Done
