### ISSUE TITLE
Create E2E test for checking Hot update feature for wsmaster

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9646]
### Description
* On first step we should clarify details for test scenario. Create test scenario.
* On second step we should implement test scenario with auto tests. The autotests also should be run on CI infrastructure.
The depended issues: 
- https://github.com/eclipse/che/issues/9415
- https://github.com/eclipse/che/issues/9414

**Comment by dmytro-ndp** [comment]
CI job to check _Recreate Update Strategy_: https://ci.codenvycorp.com/view/qa/job/che-multiuser-master-ocp-recreate-strategy-test/

**Comment by Ohrimenko1988** [comment]
Done:
 - https://github.com/eclipse/che/pull/10091 
 - https://github.com/eclipse/che/pull/10176
