### ISSUE TITLE
Can't start a project of a fresh install Eclipse Che

### ISSUE THREAD

**Issue by krocebow** [eclipse-che/che#965]
Hello,

I'm running eclipse che server on a raspberry pi, the dashboard loads but when I try to create a php project I get this error :

`2016-04-05 07:59:17,406[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 610]    - Error response from docker API, status: 500, message: Cannot start container c007d23beae5c96643824d4e6a58544b2f8b685b4bb1b67e44713aebf264b756: [9] System error: exec format error`

`org.eclipse.che.api.machine.server.exception.MachineException: Error response from docker API, status: 500, message: Cannot start container c007d23beae5c96643824d4e6a58544b2f8b685b4bb1b67e44713aebf264b756: [9] System error: exec format error`

Is this something that's caused by my system or is it related to docker?

**Comment by ghost** [comment]
@krocebow this error is caused by using a docker image that is not built for ARM7.

You may want to try to build arm7 image. This tutorial will surely help https://blog.benjamin-cabe.com/2016/04/01/running-eclipse-che-on-a-raspberry-pi

**Comment by krocebow** [comment]
This is the exact tutorial I used to install Che. Maybe something is missing?

I made sure to follow very carefully all the steps on the tutorial but it doesn't work. I'm just going to let it down, it is supposed to be few clicks to get it run ... its not the case!

**Comment by ghost** [comment]
For some reason, Che seems to use the default images. Can you run `docker images` to see what image has been pulled?

**Comment by krocebow** [comment]
I did what you asked for : 
1. codenvy/php                                                  latest              d4c591b67fd9        4 days ago          678.4 MB
2. eclipse-che/che_workspace0g381s4750rebqp8_ws-machine_b5zvk   latest              d4c591b67fd9        4 days ago          678.4 MB
3. eclipse-che/che_workspace0g381s4750rebqp8_ws-machine_m6mod   latest              d4c591b67fd9        4 days ago          678.4 MB
4. eclipse-che/che_workspaceicgltlmlagk3jnpj_ws-machine_x48lh   latest              d4c591b67fd9        4 days ago          678.4 MB
5. eclipse-che/che_workspacejs3nbte7rzafn6nn_ws-machine_qhrcm   latest              d4c591b67fd9        4 days ago          678.4 MB
6. kartben/armhf-che-jdk8                                       latest              15fd9487b6f0        6 days ago          520.4 MB
7. armv7/armhf-java8                                            latest              272fe4453397        6 months ago        464.1 MB

I see the arm images, I still don't know why it don't work.

**Comment by ghost** [comment]
@krocebow So, what happens if you create a workspace from a custom stack:

`FROM kartben/armhf-che-jdk8`

**Comment by ghost** [comment]
@krocebow any update on the problem you have faced?

**Comment by krocebow** [comment]
After using the image you specified the project loads but no way on adding php or mysql so I just gave up.

**Comment by ghost** [comment]
@krocebow all you need is to build your own image on top of what works for you, push it to DockerHub and use in Che.

**Comment by ddementieva** [comment]
Closing the issue. Do not hesitate to reopen if you have more questions or face issues.
