### ISSUE TITLE
Update "Dashboard" selenium tests according to test plan

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#9651]
### Description

We have a test plan for "Dashboard" functionality. It describes all "Dashboard" functionality. So we should update existing selenium "Dashboard" tests according to this document: https://docs.google.com/document/d/1HbU9rzto8wT-6CFE8GFPi3BEW60suVmSmxDkomqbxwQ/edit?pli=1#heading=h.4i4oqi284cre 

**It gives next advantages:**
 - Monitoring of the covering by selenium tests
 - Ability to cover by tests the most important functionality firstly and after that move to the secondary functionality 
 - Ability to reach a high level of the quality

**Progress:**
 - [x] Revise and update "Dashboard" selenium tests in "Workspaces" section https://github.com/eclipse/che/issues/9652
- [x] Revise and update 'Dashboard' selenium tests in the 'Factory' section #9785

**Comment by rhopp** [comment]
I don't think we will be extending the current dashboard tests at this time. Closing.
