### ISSUE TITLE
External libraries: "Can't read file, it does not exist: xxx"

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#9655]
### Reproduction Steps
Try to open any file in external libraries

AR:
Exception at org.eclipse.che.api.editor.server.impl.EditorWorkingCopyManager#createWorkingCopy (6.4.0):
![cannothandlefile3](https://user-images.githubusercontent.com/2270831/39773194-56e40908-5308-11e8-8b0f-50dc67fc43c4.png)

**OS and version:**    
Windows 10, Eclipse Che 6.3.0, 6.4.0, 6.4.1

**Comment by eivantsov** [comment]
@vparfonov the file opens just fine. However, ws-agent log spits an error out. Is this expected?

**Comment by RomanNikitenko** [comment]
AFAIK we create working copies for opened editors to have ability to handle editor changes on server side (java reconcile operations when autosave is turned off, for example).
But these ones are redundant in this case.
Also we have related issue https://github.com/eclipse/che/issues/8984
