### ISSUE TITLE
Hot update testing on working master

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9657]
### Description
We need to test hot update procedure. Proposed scenario: run hot update several times during selenium testing.

**Comment by sleshchenko** [comment]
During manually testing of Rolling Update functionality is reproduced the issue with failed liveness probes . Will try to tune liveness probes configurations.

<details>
<summary>OCP Events Screenshot</summary>

![screenshot from 2018-05-16 12-47-26](https://user-images.githubusercontent.com/5887312/40109981-819e7142-5907-11e8-8edc-b97e6941c3e2.png)
</details>
