### ISSUE TITLE
The last letter of che-clip-the-middle-start is displayed incorrectly

### ISSUE THREAD

**Issue by Katka92** [eclipse-che/che#9664]
### Description
When workspace name is short and the last fourth symbol is e. g. "d", it is displayed incorrectly - it seems like "a" (just without the top line). When I zoomed in, I found out that the letter is correct but a little bit cut. 

### Reproduction Steps
Create workspace, which name ends with d + 3 leters (e. g. kdtkp). See the left column - the name is in italics and is displayed incorrectly. When running workspace, the name is displayed without italics and is correct. 

**OS and version:**    
Che on rhche.openshift.io version 6.4.1 
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Diagnostics:** 
![screenshot from 2018-05-10 14-04-11](https://user-images.githubusercontent.com/29278800/39869882-a1ae3f64-545f-11e8-9958-61de0adebed4.png)

![screenshot from 2018-05-10 14-07-06](https://user-images.githubusercontent.com/29278800/39869888-a8b34c64-545f-11e8-9d40-6fcf530be3f1.png)

**Comment by SkorikSergey** [comment]
Similar issue https://github.com/eclipse/che/issues/7445.

**Comment by Katka92** [comment]
This issue is still present in 7.1.0.
/remove-lifecycle stale
