### ISSUE TITLE
Any samples on extending Che to add a new remote debugger for a new language?

### ISSUE THREAD

**Issue by venkatzhub** [eclipse-che/che#9673]
### Description

We are looking to extend Che to add in support for additional languages. Adding the languages using the LSP is straight forward, but I was unable to find any pointers on how to add in a new remote debugger for the new language we are planning to add the support for. Are there any samples/extension docs that we can look at?

### Reproduction Steps
None - it is a question not a bug. 

**OS and version:**    

**Diagnostics:**

**Comment by eivantsov** [comment]
@lilcubby debugger protocol has not been yet integrated.

@tolusha is working on it to bring it to Theia.

**Comment by lilcubby** [comment]
@eivantsov - Thank you. 

@tolusha - Any rough timeline as to when debugger protocol would be integrated?

**Comment by tolusha** [comment]
@lilcubby 
It is hard to estimate. I would say 2 month for something tangible.

**Comment by lilcubby** [comment]
Thank you - all I was looking for was a rough timeframe.
