### ISSUE TITLE
How to manage mutli-user workspace

### ISSUE THREAD

**Issue by fanntom** [eclipse-che/che#9677]
Hi, I currently run a Multi-User version of Eclipse Che with Docker.
I'd like to have the Admin user be able to view and manage other users' workspaces.
Is there an existing way to do so?

**Comment by eivantsov** [comment]
@fanntom setting this property to true may help https://github.com/eclipse/che/blob/master/dockerfiles/init/manifests/che.env#L418

**Comment by fanntom** [comment]
@eivantsov so I set the value as so:
![ubuntu 64-bit-2018-05-11-23-11-41](https://user-images.githubusercontent.com/19740384/39928604-c9504190-5570-11e8-96ee-06b601b1a066.png)

however, when I access Eclipse Che via admin account, I still do not see other member's work spaces.
I am currently using Eclipse Che on Ubuntu 16.04 on VMware Workstation with Docker..

**Comment by eivantsov** [comment]
You will not see them in Dashboard and there are no tools that will let you see those. You can use REST methods however to GET, or DELETE them.

**Comment by fanntom** [comment]
Thank you for your reply!
