### ISSUE TITLE
Define the editor api workflow needed to implement teletype plugin

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#9679]
Subtask of https://github.com/eclipse/che/issues/9434

**Comment by evidolob** [comment]
@sunix Can you provide list of methods that you are use for teletype plugin

**Comment by ashumilova** [comment]
Almost all work is done on Editor API already.

**Comment by sunix** [comment]
here it is

- get opened editors
- get opened editor
- put/remove markers (cursor) - position row/column
- on cursor/selection activity
    - selection start.row
    - selection start.col
    - selection end.row
    - selection end.col

- on document ready
- on document opened
- on document active
- on document changing (about to change)
    - startPosition.getrow
    - startPosition.getColumn
    - endPosition.getrow
    - endPosition.getcolumn
    - newText

- document getContents
- document replace(oldstartrow, oldstartcolumn, oldendrow, oldendcolumn, text)
- document setCursorPosition
- document setContents (could be using replace as well)


- open a document

Nice to have but optional
- custumize user markers (css, add text, image)

**Comment by sunix** [comment]
Also would be nice to have the ability to open an editor that is not in the file system. have a virtual file system but maybe this is out of scope.
