### ISSUE TITLE
Eclipse Che stuck on Loading Workspaces with flashing Che logo.

### ISSUE THREAD

**Issue by fanntom** [eclipse-che/che#9692]
### Description
Hi I'm running an Amazon EC2 Instance that has Ubuntu 16.04 LTS installed.
I'm trying to deploy Eclipse Che with the following command:
sudo docker run -it -e CHE_MULTIUSER=true -e CHE_HOST={amazon ec2 Elastic IP} -v /var/run/docker.sock:/var/run/docker.sock -v ~/.che-multiuser:/data eclipse/che start'
And if the public ip for that EC2 instance is 123.456.789.012, 
I added http://123.456.789.012:8080/* to the redirect ui and http://123.456.789.012:8080 to the web origins.
However if I try to access http://123.456.789.012:8080 in my browser, the browser hangs on Loading Workspaces with a flashing Che Logo.

I have no problems accessing http://123.456.789.012:5050

**OS and version:**    
Ubuntu 16.04 LTS with Eclipse Che 6.5.0
**Diagnostics:** 
When I run:
sudo docker logs -f che, I don't get any additional logs even when I try to visit  http://123.456.789.012:8080

**Comment by eivantsov** [comment]
@fanntom your CHE_HOST should be a public IP.

Can you open browser dev console and share a screenshot with an error?

**Comment by fanntom** [comment]
@eivantsov where can i find the browser dev console?

**Comment by eivantsov** [comment]
https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by fanntom** [comment]
[13.209.21.113-1526370690183.log](https://github.com/eclipse/che/files/2003907/13.209.21.113-1526370690183.log)
![devconsole](https://user-images.githubusercontent.com/19740384/40043758-6dabd4ec-5860-11e8-8262-63e39a6fc2d4.png)
![keycloakconfig](https://user-images.githubusercontent.com/19740384/40043759-6dd494e0-5860-11e8-9f4b-b1710788da66.png)
Here is the dev console logfile, image, and keycloak che-public settings @eivantsov

**Comment by eivantsov** [comment]
@fanntom your CHE_HOST should be a public IP ie the one that your browser can access. The screenshot tells that Keycloak script cannot be loaded since it uses AWS internal IP. Try setting DOCKER_HOST to a public IP

Also, you need to make sure ports 5050 and the ephemeral port range aren't filtered.

**Comment by fanntom** [comment]
what would be the expected port range???

**Comment by eivantsov** [comment]
https://www.eclipse.org/che/docs/docker-multi-user.html#system-requirements

**Comment by fanntom** [comment]
Thank you @eivantsov for helping me through! I should've read the Docs page more carefully.
