### ISSUE TITLE
It is impossible to create machine with custom name in the "New Stack" page

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#9700]
### Reproduction Steps
 - Click on the "Stacks" button on the dashboard
 - In the opened page click on the "Add Stack" button
 - In the opened page click on the "Add" button in "Machines" section
 - In the opened form specify "custom" name and click on the "Add" button
 - Pay attention to the name of the added machine

**Expected behavior:**
The added machine has "CUSTOM" name

**Observed behavior:**
The added machine has "UNDEFINED" name

**OS and version:**    
Che 6.6.0 ; Chrome 66.0 ; Fedora 25

**Attachment:**
![out](https://user-images.githubusercontent.com/22724619/40050131-3eb8e0c4-583f-11e8-978e-e45f114a0e27.gif)

**Diagnostics:**

**Comment by SkorikSergey** [comment]
Is not reproduced in Che 6.19.0-SNAPSHOT.
