### ISSUE TITLE
How to share stacks between users?

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9702]
Is it possible to share stacks between users in a selfhosted che multiuser environment?
We store the stack configuration JSONs in GIT and share them with the team. It's not possible to access the stacks someone created in che and also it's not possible to create a stack with the same name someone else already created. This leads to us prefixing our stack names. Is there any smarter solution?
Thanks for your help!

**Comment by eivantsov** [comment]
@ex-q https://github.com/eclipse/che/issues/9579#issuecomment-385961484

Will update docs with it soon

**Comment by ex-q** [comment]
Thanks a lot!
