### ISSUE TITLE
Eclipse che version upgradation from 6.0 to 6.4

### ISSUE THREAD

**Issue by Mohdzaved2434** [eclipse-che/che#9707]
Hi All,

     Where can I see the changes done in package structure while upgrading the Eclipse che from one version to another?

**Comment by eivantsov** [comment]
@Mohdzaved2434 what exactly do you mean by package structure? Source code?

**Comment by Mohdzaved2434** [comment]
@eivantsov like earlier 6.0.0-M2 ProcessStartResponseDto class was present in 
org.eclipse.che.ide.api.command.exec.dto package 
but in 6.0.0 this class is present in following package
org.eclipse.che.agent.exec.shared.dto package.

and where can we see changes done in classes while upgrading the eclipse che version ?

**Comment by eivantsov** [comment]
There's changelog https://github.com/eclipse/che/blob/master/CHANGELOG.md however it is unlikely that issue title contains smth like this.

**Comment by Mohdzaved2434** [comment]
@eivantsov  Thanks
