### ISSUE TITLE
Use the fixed version of Theia in eclipse/che-theia image

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9716]
Due to unpredictable number of fails of workspace with Theia IDE inside - there is need to have fixed version of Theia inside eclipse/che-theia image along with the fixed versions of used extensions. This will avoid version compatibility problems, may occur both on application build or launching stages.

Work was started in this [PR](https://github.com/eclipse/che/pull/9684)

**Comment by AndrienkoAleksandr** [comment]
Done.
