### ISSUE TITLE
Prepare build for eclipse/che-theia image on CI

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9718]
This task has the following requirements:
- [x] the build of the image from the following [dockerfile](https://github.com/eclipse/che/blob/master/dockerfiles/theia/Dockerfile) should be handled on daily basis, same as for other nightly images we have in Сhe, and published on DockerHub
- [x] on Che release the eclipse/che-theia should have complex version number - [che version]-[theia version] (example, eclipse/che-theia:6.11.0-0.3.8), in case of Che release only Che version part changes, theia one will change manually on theia releases
- [x] stacks.json should be updated as well with the tagged version

**Comment by riuvshin** [comment]
@ashumilova just a few questions:
1) `eclipse/che-theia:nightly ` is this right theia image name which should be generated on daily basis?

2) which of stacks.json should be updated 
```
ide/che-core-ide-stacks/src/main/resources/stacks.json
```
OR
```
wsmaster/che-core-api-workspace/src/test/resources/stacks.json
```
3) where can I get actual theia tag to use?

**Comment by ashumilova** [comment]
1. eclipse/che-theia:nightly-0.3.8 or maybe change the order to have - eclipse/che-theia:0.3.8-nightly
@benoitf wdyt?

2. The stacks are the following:
https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L56
https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L126

3. https://github.com/eclipse/che/tree/master/dockerfiles/theia
https://hub.docker.com/r/eclipse/che-theia/
https://hub.docker.com/r/theiaide/theia/

**Comment by ashumilova** [comment]
FYI - 0.3.10 - for Theia current version

**Comment by riuvshin** [comment]
nightly tag is already in place: https://hub.docker.com/r/eclipse/che-theia/tags/
