### ISSUE TITLE
[Theia][Plugin]Rework SSH extension to SSH plugin

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9720]
The existing https://github.com/eclipse/che-theia-ssh-plugin is developed based on the existing extensibility model in Theia IDE. But as far as new plugin model is on it's way and will be used in Che as the main one - there is need to rework SSH extension to SSH plugin.

**Comment by vinokurig** [comment]
Depends on: #9980, #9986

**Comment by benoitf** [comment]
note that then the plug-in needs to be embedded instead of the extension
like https://github.com/eclipse/che/pull/11718
