### ISSUE TITLE
Cannot select text in dialogs

### ISSUE THREAD

**Issue by bostrt** [eclipse-che/che#9727]
### Description
I have two specific examples of a possibly global issue with Che's dialogs:

1) If there is a workspace error, I cannot select and copy the text from the dialog. Screenshot attached of a long error message that I would want to copy/paste to someone in order to get help.
2) Cannot select and copy text from the About Eclipse Che dialog. This would be needed when I have to share my revision number in an issue (this one for example).

**OS and version:**    
Eclipse Che 6.6.0-SNAPSHOT, Revision 24bc9470b0a20330, Build Time 2018-05-15 17:09:04
Fedora 26
Google Chrome 66 and FireFox 59

**Screenshot for Issue 1**
![screenshot from 2018-05-16 13-47-43](https://user-images.githubusercontent.com/215290/40134545-b44598c4-5910-11e8-9496-7966417bff12.png)

**Comment by rhopp** [comment]
@vzhukovskii  Do I get it right, that this was fixed only for the `About Dialog` but not for the errors during startup? To me it seems, that this issue should not be closed yet.
