### ISSUE TITLE
Update and document Che Ansible Playbook Bundle

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#9728]
An APB to deploy Che on OCP exists: https://github.com/ansibleplaybookbundle/eclipse-che-apb

This task is about
- Updating the template used to deploy Che upstream (if needed) 
- Document how to use it

**Comment by l0rd** [comment]
cc @slemeur

**Comment by l0rd** [comment]
I have opened a PR to update/fix Che template: https://github.com/ansibleplaybookbundle/eclipse-che-apb/pull/10

Now the APB works. At least the integration test works fine (Che deployment and start of a workspace). To run the test locally:

```bash
# login first
oc login  ....

export REGISTRY=`oc get svc/docker-registry -n default --as system:admin --template '{{.spec.clusterIP}}:{{index .spec.ports 0 "port"}}'`
export APB_NAME=eclipse-che-apb
export OC_USER=`oc whoami` OC_PASS=`oc whoami -t`

# Build the APB
# eval $(minishift docker-env)
git clone -b update-che-template git@github.com:l0rd/eclipse-che-apb.git && cd eclipse-che-apb
docker login -u ${OC_USER} -p ${OC_PASS} ${REGISTRY}
docker build -t $APB_NAME .
docker tag "${APB_NAME}" "${REGISTRY}/${APB_NAME}/${APB_NAME}"
docker push "${REGISTRY}/${APB_NAME}/${APB_NAME}"

# Create the apb service account used to run Che
oc create sa apb
oc adm policy add-role-to-user admin -z apb

# Run the tests
oc run "${APB_NAME}-test" -it --restart='Never' --image "${REGISTRY}/${APB_NAME}/${APB_NAME}" --env "OPENSHIFT_TOKEN=${OC_PASS}" --env "OPENSHIFT_TARGET=https://kubernetes.default.svc" --env "POD_NAME=${APB_NAME}-test" --env "POD_NAMESPACE=${APB_NAME}" --overrides='{"apiVersion":"v1","spec":{"serviceAccountName":"apb"}}' -- test -e namespace=${APB_NAME}
```

Things that still need to be fixed:
- Write documentation on how to use it
- Currently `$OPENSHIFT_TOKEN` (OpenShift OAuth Token) is prompted to deploy Che but a service account should be used instead.
- Currently `$CHE_OAUTH_GITHUB_CLIENTID` (GitHub client ID/secret) is prompted to deploy Che but it doesn't really makes sense.
- We need to add TLS support (as an option in the Che catalog)
- Which of the following Che flavours should we support? 
  - single user Che
  - multi user Che
  - workspaces and wsmaster in the same namespace 
  - create a new namespace for every workspace using Che token 
  - create a new namespace for every workspace using users tokens

**Comment by gorkem** [comment]
Do we need to select only one Che flavor?  Can we do multi-user with user choosing one of the strategies?

**Comment by eivantsov** [comment]
@l0rd @gorkem my thoughts:

* having APB for a single user Che is an overkill I think - do we really need it?
* by default we should use che SA and thus create ws objects in the same namespace with Che server. This is the best way to get started with Che without having any auth problems. An admin can deploy and try Che and then reconfigure it to use token/credentials.
* as to having OpenShift oAuth in place: can APB create oAuth client at a cluster scope? If yes, then we should create it (prompt for client ID and secret), register an OpenShift v3 identity provider with Keycloak and update Che deployment env with provider name.
* Yes, we do not need GitHub client ID and secret right away. First off, these are the envs that work only in a single user che. Secondly, an admin needs to register an app on GitHub side to get ID and secret, but to do so a callback URL is required and one has it after Che route is created.

**Comment by slemeur** [comment]
Agree with @gorkem : We should definitely be looking at having a single APB which support the different flavors and options. 

@l0rd : The options that you listed are the right ones. 
- We need to make sure that it's possible to install Che with secure mode or not. 

As for the different options:
1. workspaces and wsmaster in the same namespace
2. create a new namespace for every workspace using Che token
3. create a new namespace for every workspace using users tokens

Have we got a way to explain the differences to the admin installing Che? He might not be able to understand the impacts of this choice. 
For the default choice, we should think about what is the option which is the most valuable approach - I don't think having workspaces/wsmaster in the same namespace is appropriated when you are looking to bring a team of developers. This solution fits mainly for "quick trials" or "Che developers" use cases. I would not make it the default choice - I would prefer creating workspaces/namespaces with user's token. 

The single-user mode: ideally we don't want to have different methods for installing Che, it should be unified and we should see that with the perspective of the maintenance burden. The single user mode is mostly for the developers on Che. Near team, we are going to introduce the self hosting and I think it decrease the value of the single-user. Moreover, I'm not sure, that if a developer is creating his custom Che,  doing the inner development loop with the APB is the simplest/fastest method. 
@l0rd : How would it work? 

I'm fine with supporting only the multi-user mode with the APB - and having in docs, the single-user mode documented.

**Comment by garagatyi** [comment]
@eivantsov @l0rd is this issue still actual?

**Comment by skabashnyuk** [comment]
@l0rd Is this issue still relevant?

**Comment by l0rd** [comment]
No that's not relevant anymore
