### ISSUE TITLE
Preferences UI for Theia IDE

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#9730]
Create a widget for viewing and adding preferences in Theia IDE.
The idea is to have something similar to preferences in VSCode:
 
![screenshot from 2018-05-17 10-59-43](https://user-images.githubusercontent.com/7668752/40164355-f91c199e-59c1-11e8-9fe3-b274248f1b55.jpg)

**Comment by vinokurig** [comment]
@slemeur According to last PR remarks from Theia team: https://github.com/theia-ide/theia/pull/1983#pullrequestreview-129922124 This issue is going to be reworked one more time. As for now the preferences action opens two different widgets (preferences tree and editor with preferences file) in spited mode. As was mentioned in the PR it is needed to be rework the widget to use one common widget.

**Comment by slemeur** [comment]
Thanks @vinokurig . Please create subtasks for that and also list the different improvements you are looking after (based on the demo feedbacks).

**Comment by vinokurig** [comment]
@slemeur I am not sure that the feedback fits Theia requirements.

**Comment by vinokurig** [comment]
https://github.com/theia-ide/theia/pull/1983
