### ISSUE TITLE
Failed to start che

### ISSUE THREAD

**Issue by habeascorpse** [eclipse-che/che#9734]
Hello,

i'm trying to start eclipse che with the follow command:

> docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /var/volumes/eclipse/:/data -e CHE_HOST=x.x.x.x -e CHE_MULTIUSER=true  eclipse/che:latest start

and then the follow msg is displayed on the console:

> INFO: (che init): Installing configuration and bootstrap variables:
> INFO: (che init):   CHE_HOST=x.x.x.x
> INFO: (che init):   CHE_VERSION=6.5.0
> INFO: (che init):   CHE_CONFIG=/var/volumes/eclipse/
> INFO: (che init):   CHE_INSTANCE=/var/volumes/eclipse//instance
> INFO: (che config): Generating che configuration...
> INFO: (che config): Customizing docker-compose for running in a container
> INFO: (che start): Preflight checks
> WARNING: No swap limit support
>          mem (1.5 GiB):           [OK]
>          disk (100 MB):           [OK]
>          port 8080 (http):        [AVAILABLE]
>          conn (browser => ws):    [OK]
>          conn (server => ws):     [OK]
> 
> INFO: (che start): Starting containers...
> INFO: (che start): Services booting...
> INFO: (che start): Server logs at "docker logs -f che"
> INFO: (che start): Booted and reachable
> INFO: (che start): Ver: 6.5.0
> INFO: (che start): Use: http://x.x.x.x:8080
> INFO: (che start): API: http://x.x.x.x:8080/swagger

But, when i try to access the URL on browser, only show a black screen with title Loading Dashboard..

Additional Information:
OS: Ubuntu 18.04 LTS (GNU/Linux 4.15.0-20-generic x86_64
Docker: 18.05.0-ce

**Comment by eivantsov** [comment]
@habeascorpse, a couple of things:

* your CHE_HOST should be a public IP
* ports 8080, 5050 and the ephemeral port range need to be accessible

If you open your browser dev console and refresh the page, you will probably see an error signaling that Keycloak initialization fails, probably (my guess) due to ERR_CONNECTION_TIMED_OUT or something like that. Can you provide a screenshot with dev console opened? Also, pay attention to ports I have mentioned above.

**Comment by eivantsov** [comment]
@habeascorpse Can you reach `http://186.219.240.93:5050/auth`? Credentials are `admin:admin`

**Comment by eivantsov** [comment]
And I have got the same error. Must be a network issues. Can you reach a different webserver running on that node? Say, stop Che, and run nginx in a container?

**Comment by habeascorpse** [comment]
I access the :5050/auth ok.
and yes, i can access others webservices.

**Comment by eivantsov** [comment]
I'd also check access logs as well:

```
docker exec -ti che bash
cat /data/logs/logs/localhost-access.log
```

**Comment by habeascorpse** [comment]
Hi,
i found the error. It's was a network issue.

thank you for the help me.
