### ISSUE TITLE
Tracking bug: minishift Che extension bails (minishift/minishift/2391)

### ISSUE THREAD

**Issue by dneary** [eclipse-che/che#9735]
Reference issue: https://github.com/minishift/minishift/issues/2391

### Description
minishift installation of Eclipse Che extension appears to complete successfully, but the Che service fails to start afterwards. See [mini-che is failing to start on minishift](https://github.com/minishift/minishift/issues/2391) for details.

**Comment by eivantsov** [comment]
@dneary this isn't an Eclipse Che bug but a bad PV issue with MiniShift. I prefer to close this one and track  an issue in MiniShift repo - I'm already helping there.

**Comment by dneary** [comment]
Can we improve the error notifications on PV related issues to make it easier for someone to diagnose (and know how to fix) the issue?

Closing this ticket.
