### ISSUE TITLE
Supporting Gentoo docker containers

### ISSUE THREAD

**Issue by claam** [eclipse-che/che#9739]
Hello there.

I didn't see this feature in your roadmap nor in issues. Have you planned to do that in the future ?

kind/question

**Comment by eivantsov** [comment]
@claam do you mean containers with Gentoo OS or any special container type (sorry I am not very knowledgeable on Gentoo containers)

**Comment by claam** [comment]
@eivantsov I guess both. My problem was with Gentoo OS. I got something like "unrecognized Linux distrib" when I tried to open a terminal or other installers. My solution was to create an additional ubuntu container, and both shares source code with a volume. However, I have no idea of how build the code without installers.

**Comment by eivantsov** [comment]
@claam yes, installers do not expect this type of OS

**Comment by claam** [comment]
@eivantsov okay, so to go back to the initial question, do you plan to support docker containers with such OS ?

**Comment by eivantsov** [comment]
I think no. But you can issue a PR. I can show you how to fix it for Gentoo if you are interested.

**Comment by sr229** [comment]
Gentoo will not be officially supported by Eclipse Che, but a PR would suffice to add Gentoo as a Stack Base.

**Comment by claam** [comment]
Thanks for your answers, I will take a look at that.
I close the issue since I have the answer.
