### ISSUE TITLE
Workspace start hangs up on bootstrapping phase when Rolling Update is in progress

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#9740]
### Description
Bootstrapper uses Che Server Route URL for notifying Che Server when bootstrapping is finished. And here is an issue because there is a possible (and reproducible) case when The Stopping Che Server is starting a workspace and waiting bootstrapper events BUT bootstrapper connects to Che Server Route URL and actually it is connected to the NEW Che Server instance. In this way, old Che Server doesn't receive that event that workspace is bootstrapped and bootstrapping wait timeout occurs. 
The possible solution here is implementing distributed messaging service.
Also proving Che Server IP may solve an issue on a local OS but it won't work on a multicluster case, like OSIO, where Che Server is started on one OS cluster and workspaces on another one.

**OS and version:**    

**Diagnostics:**

**Comment by mshaposhnik** [comment]
At this moment this is an expected behavior due to Che6 architecture, 
and cannot be changed or fixed in a short or mid-time perspective. 
We described that in admin docs/update guide as a known issue:
https://github.com/eclipse/che-docs/blob/master/src/main/pages/setup-openshift/admin-guide.md#known-issues

**Comment by garagatyi** [comment]
@sleshchenko I think you've addressed this issue already.

**Comment by sleshchenko** [comment]
@garagatyi No, I haven't. Actually, I implemented components that will get rid of hanging workspaces but this issue is more about fixing a case when workspace become hanging. I think it may be fixed by using of distributed messaging service.
