### ISSUE TITLE
Tools for formatting and debugging

### ISSUE THREAD

**Issue by kostiamol** [eclipse-che/che#9744]
Is there any way to integrate formatting tools (go fmt) and file watchers? What about debugging tools for languages other than Java (particularly, for Go)?

**Comment by eivantsov** [comment]
@kostiamol there's an ongoing effort to integrate Theia IDE into Che workspaces. This integration brings along lots of perks like LSP, debug protocol etc. So, the answer is yes, but for the next generation of Che with an updated IDE.

I think with Theia integrating https://github.com/derekparker/delve will be much easier, so having VS Code like experience isn't impossible.

**Comment by kostiamol** [comment]
@eivantsov could you tell the estimated date for all that stuff?

**Comment by eivantsov** [comment]
I cannot. The only thing I can recommend is to follow announcements and roadmap ETA
