### ISSUE TITLE
Eclipse Che Multiuser dashboard

### ISSUE THREAD

**Issue by LuisCastilloV98** [eclipse-che/che#9748]
### Description

Once complete the installation of Eclipse-Che Multiuser, the Admin allowed me to enter correctly (port 5050) but when entering the dashboard (port 8080) it is cycled by loading the eclipse image and never enters, any idea why this happens ?

![capture](https://user-images.githubusercontent.com/28116477/40247032-37cafe8c-5a88-11e8-91af-f7ace257f5a5.PNG)

![capture](https://user-images.githubusercontent.com/28116477/40248792-49dcda18-5a8e-11e8-9d55-37923bd15ba0.PNG)

**Comment by eivantsov** [comment]
@Kyubi98 
Can you run and share the output?
`docker logs -f che`

**Comment by Kyubi98** [comment]
Good, sorry for the delay, I run the command and the result was the following:

[Resultado.txt](https://github.com/eclipse/che/files/2019588/Resultado.txt)

![respuesta](https://user-images.githubusercontent.com/28116477/40270265-ee29d374-5b46-11e8-893d-e063f0bb32b2.PNG)

**Comment by eivantsov** [comment]
@Kyubi98 you have incorrectly started Che multi user.

The error says:

```
Error injecting constructor, java.lang.RuntimeException: Exception while retrieving OpenId configuration from endpoint: http://:5050/auth/realms/che/.well-known/openid-configuration
```

There's no IP in the endpoint.

Can you share your docker run syntax?

**Comment by eivantsov** [comment]
Closed due to inactivity. Explicitly passing CHE_HOST should do the trick
