### ISSUE TITLE
Self diagnostic tool Finished With Error

### ISSUE THREAD

**Issue by Blendman974** [eclipse-che/che#9749]
Eclipse che self diagnostic finished with error : 

No reply of websocket test after 5 seconds. Websocket is failing to connect to ws://eclipse.aspaku.com:9080/api/ws?token=[...]

![capture d ecran_2018-05-19_13-51-25](https://user-images.githubusercontent.com/35555508/40267304-caca4ab0-5b6b-11e8-9970-39593c8cde46.png)

Indeed /api/ws does not exist : 
![capture d ecran_2018-05-19_13-52-45](https://user-images.githubusercontent.com/35555508/40267372-0dda96d4-5b6c-11e8-8957-b7e6deab5bfd.png)

There is no error in keycloak and che containers logs and swagger is running : 
![capture d ecran_2018-05-19_13-57-26](https://user-images.githubusercontent.com/35555508/40267399-c0b8ffc0-5b6c-11e8-9f94-4aac0bfec6d9.png)

What I think is that websocket is no longer at "api/ws" and is now located at "api/websocket" : 

![capture d ecran_2018-05-19_13-58-22](https://user-images.githubusercontent.com/35555508/40267425-13f94168-5b6d-11e8-8339-49d5ae2fde41.png)

**Comment by eivantsov** [comment]
@Blendman974 thanks for reporting this.

@ashumilova another bug report with a diagnostics tool. It does return 404

**Comment by SkorikSergey** [comment]
This issue fixed by https://github.com/eclipse/che/pull/9757.
