### ISSUE TITLE
Setup Ubuntu server - Virtualbox 

### ISSUE THREAD

**Issue by xtbe** [eclipse-che/che#975]
Hi,

I've installed the latest Che version on a Ubuntu server VM running on Virtualbox

Server version : Ubuntu Server 14.04 LTS
Kernel version : 4.2.0-35-generic
Java version installed : 1.8.0_77-b03
Docker server version installed : 1.10.3
Docker client version installed : 1.10.3
Virtualbox : 5.0.16 r105871
Port forwarding on port 8080 has been set up in order to be accessible from the host system

I manage to get Eclipse Che started and can access it via my browser
I choose to create a new simple HelloWorld Java project

After doing this I get the build screen but the process get stucked at "Inject and start workspace agent"
I get this message

![image](https://cloud.githubusercontent.com/assets/909796/14310426/073530d2-fbe2-11e5-90be-a2d713d5513d.png)

I increased the timeout in the conf/che.properties file however I keep getting this error

![image](https://cloud.githubusercontent.com/assets/909796/14310434/185c58fe-fbe2-11e5-8612-76725e52ce31.png)

What I'm missing that this doesn't work.

I was able to create an empty Java container and get to the IDE but there the workspace agent remains in initializing and when I create a small program I'm also not able to display the console.

So it looks like i'm missing something ? Any advice ? Or doesn't it work with this kind of setup?

Thank you in advance for the help and feedback!
Tom

**Comment by ghost** [comment]
If you are running Che in a VM, you should either setup port forwarding in VirtualBox for 32768-65535 port range (in fact, 20-30 ports is enough if you do not run a lot of workspaces at a time) or run che with `-r:$IP` flag where `$IP` is IP of your VM.

**Comment by xtbe** [comment]
Hi,

I made some additional tests

My network setup on VirtualBox is NAT

I opened ports 32768 - 32788 -> not working
I started Che with the ip address "-r" -> not working

I changed the network adapter settings of my VirtualBox to host-only adapter
You can't have port forwarding so i started che with the ip address of the vm

bin/che.sh -r 192.168.56.101 -i run --skip:uid

With this command i was able to connect on the host via the ip address above.
The container/machine seems now to be created however I get another error message

![image](https://cloud.githubusercontent.com/assets/909796/14314750/69f76976-fbf9-11e5-8d45-47cb272038c4.png)

![image](https://cloud.githubusercontent.com/assets/909796/14314754/76453ef6-fbf9-11e5-8975-9849196e2f7e.png)

So looks like there's a little bit progress but we're not yet there

**Comment by ghost** [comment]
Drop `-i` - you do not need it here.

**Comment by xtbe** [comment]
Ok, leaving that one out did the trick and I got further in the process.

Now the issue is that with "host-only adapter" network setup, the sample project can't be created because with "host-only" the VM can't reach out to the net.

So i'm stuck with creating an empty workspace or I need to find another working network setup solution with Virtualbox.

**Comment by ghost** [comment]
Looks like a process in the container cannot reach out to the world. You need to make sure you can ping github.com from within a container. Similar issue here - https://github.com/eclipse/che/issues/979

**Comment by xtbe** [comment]
Hi,

I was able to get it working ! 

I reversed my Virtualbox network setup back to NAT and added some additional ports in the port forwarding based on the information on https://eclipse-che.readme.io/docs/networking#native-process-for-che-native-docker-for-workspace

By including these ports the VM could reach the outworld, create the workspace and project, start the agent and run the terminal

For reference I include my port forwarding setup which works for Virtualbox 

![image](https://cloud.githubusercontent.com/assets/909796/14319316/0736f62c-fc11-11e5-87c6-6199914e756e.png)

Tnx a lot for all the help and advice !
