### ISSUE TITLE
Red Hat 6 based images do not work with ssh-agent -- `ssh-keygen -A` unknown option -A

### ISSUE THREAD

**Issue by lukasheinrich** [eclipse-che/che#9750]
### Description

For custom stacks based on Red-Hat 6, workspaces cannot start due to an older version of `openssh` that does not accept the `-A` flag. This happens even if all agents are turned off (especially the SSH agent)

I'm attaching a logfile for a stack based on the image `lukasheinrich/atlasche`

Would it be possible to rewrite the start-up script to be more portable across openssh versions?

[lukasheinrich-wksp-e7ok 2018-05-19 22_10_20.log](https://github.com/eclipse/che/files/2019778/lukasheinrich-wksp-e7ok.2018-05-19.22_10_20.log)

**Comment by eivantsov** [comment]
@lukasheinrich all ssh agent does is starts sshd. So you can install openssh in your image and start it in the entrypoint. This is where an actual error happens - https://github.com/eclipse/che/blob/master/agents/ssh/src/main/resources/installers/1.0.0/org.eclipse.che.ssh.script.sh#L151

**Comment by lukasheinrich** [comment]
hi @eivantsov,

openssh is installend but with an older version (`5.3p1-123.el6_9 `) that does not have the `-A` option in `ssh-keygen`

Also I don't exactly understand why the `sshd` daemon gets started since I explicitly turned it off

```json
{
  "name": ".ATLAS",
  "id": "stackgw9baeybc01yaou0",
  "scope": "general",
  "description": "ATLAS Stack",
  "workspaceConfig": {
    "name": "default",
    "commands": [],
    "projects": [],
    "environments": {
      "default": {
        "recipe": {
          "type": "compose",
          "content": "services:\n dev-machine:\n  image: lukasheinrich/atlasche\n",
          "contentType": "application/x-yaml"
        },
        "machines": {
          "dev-machine": {
            "attributes": {
              "memoryLimitBytes": "2147483648"
            },
            "servers": {},
            "agents": [
              "org.eclipse.che.ws-agent"
            ]
          }
        }
      }
    },
    "defaultEnv": "default",
    "links": []
  },
  "creator": "userqj84tonc93cnw3wk",
  "tags": [
  ],
  "components": []
}
```

```
host > docker run --rm -it lukasheinrich/atlasche bash
[bash][root]:atlas > yum list installed|grep openssh
openssh.x86_64                   5.3p1-123.el6_9                   @slc6-updates
openssh-clients.x86_64           5.3p1-123.el6_9                   @slc6-updates
[bash][root]:atlas > ssh-keygen -A
ssh-keygen: illegal option -- A
usage: ssh-keygen [options]
Options:
  -a trials   Number of trials for screening DH-GEX moduli.
  -B          Show bubblebabble digest of key file.
  -b bits     Number of bits in the key to create.
  -C comment  Provide new comment.
  -c          Change comment in private and public key files.
  -D pkcs11   Download public key from pkcs11 token.
  -e          Convert OpenSSH to RFC 4716 key file.
  -F hostname Find hostname in known hosts file.
  -f filename Filename of the key file.
  -G file     Generate candidates for DH-GEX moduli.
  -g          Use generic DNS resource record format.
  -H          Hash names in known_hosts file.
  -h          Generate host certificate instead of a user certificate.
  -I key_id   Key identifier to include in certificate.
  -i          Convert RFC 4716 to OpenSSH key file.
  -L          Print the contents of a certificate.
  -l          Show fingerprint of key file.
  -M memory   Amount of memory (MB) to use for generating DH-GEX moduli.
  -N phrase   Provide new passphrase.
  -O option   Specify a certificate option.
  -P phrase   Provide old passphrase.
  -p          Change passphrase of private key file.
  -q          Quiet.
  -R hostname Remove host from known_hosts file.
  -r hostname Print DNS resource record.
  -S start    Start point (hex) for generating DH-GEX moduli.
  -s ca_key   Certify keys with CA key.
  -T file     Screen candidates for DH-GEX moduli.
  -t type     Specify type of key to create.
  -V from:to  Specify certificate validity interval.
  -v          Verbose.
  -W gen      Generator to use for generating DH-GEX moduli.
  -y          Read private key file and print public key.
  -Z name,... User/host principal names to include in certificate
  -z serial   Specify a serial number.
```

**Comment by eivantsov** [comment]
@lukasheinrich jdk is required in all workspaces since this is a dependency for workspace agent.

If ssh agent is off, that script isn't executed at all.

**Comment by lukasheinrich** [comment]
Hi @eivantsov,

ok I see. I think we can install jdk. But now I am confused why the ssh-keygen line is executed. As you can see in the workspace config I disabled all agents including the SSH agent, but still see the error (i'm testing on codenvy.io)

<img width="813" alt="screenshot" src="https://user-images.githubusercontent.com/2318083/40278914-316ea698-5c3a-11e8-8aa3-2f50949d4e28.png">

**Comment by eivantsov** [comment]
```
Workspace Agent will be downloaded from Workspace Master
/root/che/ws-agent/bin/catalina.sh: line 366: /root/che/jdk1.8/bin/java: No such file or directory
/root/che/ws-agent/bin/catalina.sh: line 366: exec: /root/che/jdk1.8/bin/java: cannot execute: No such file or directory
```
This is what I get when trying to start your workspace. ws agent installer tries to install openjdk, and it seems everything is ok, however, ws agent itself cannot start as it cannot find Java probably because this symlink did not work https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/installers/1.0.3/org.eclipse.che.ws-agent.script.sh#L236

**Comment by eivantsov** [comment]
@lukasheinrich Eclipse Che != Codenvy.io

In case of codenvy.io ssh agent is on by default since it is used by rsync agent that backs up and restores workspace projects.

**Comment by eivantsov** [comment]
I recommend you install openjdk in the image and it will be ok when it is used in Eclipse Che

**Comment by lukasheinrich** [comment]
Thanks @eivantsov! That's very helpful. I understand Che and Codenvy are different. But it seems like if we wanted to make the ssh-agent compatible with Red Hat 6 we would still need to change the Che code (at the line you pointed out)

Would this be possible?

**Comment by eivantsov** [comment]
@lukasheinrich yes. However, Codenvy is in maintenance mode and it's running 5.22.x version, while Che is 6.x.

Running sshd in an entrypoint of your image should do the trick.

**Comment by lukasheinrich** [comment]
Hi @eivantsov,

sorry I think I'm missing some step. Are you saying that if I manually run sshd in the trnypoint of my image, the `ssh-keygen -A` line will not be executed?

**Comment by eivantsov** [comment]
ssh-keygen line isn't executed unless you enable ssh agent. I am talking about Eclipse Che now. Not Codenvy.

**Comment by eivantsov** [comment]
Closed due to inactivity. Installing software and deps in the base image is the best way to ensure this functionality is available in runtime.
