### ISSUE TITLE
Unexpected fail of selenium tests on OSIO

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse-che/che#9753]
### Description
We have unexpected fail of selenium tests from '**dashboard**' package on **OSIO**. The tests sometimes fail because test workspaces cannot start. We should clarify reason and fix it.

**Report with reproduced problem:**
https://ci.codenvycorp.com/view/qa/job/che-dashboard-integration-tests-prod-preview/12/Selenium_tests_report/

**Comment by SkorikSergey** [comment]
It seems when selenium tests start from a test suite there is not enough time for **OSIO** to free resource after test workspace stopped and next workspace cannot start.
![screenshot from 2018-05-18 10-10-58](https://user-images.githubusercontent.com/7760565/40295216-3c3e9b62-5ce1-11e8-8eec-fb03bc3aba62.png)

**Comment by SkorikSergey** [comment]
Issue about this problem on https://github.com/redhat-developer/rh-che:
- **Can't start workspace after DELETE of another workspace** https://github.com/redhat-developer/rh-che/issues/673

**Comment by l0rd** [comment]
This issue should be solved as soon as rh-che will be based on [6.8.0](https://github.com/redhat-developer/rh-che/blob/master/pom.xml#L19)

**Comment by SkorikSergey** [comment]
Fixed.
