### ISSUE TITLE
New plugin model doesn't work in electron version of Theia

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#9767]
### Description
Hosted plugin doesn't work electron mode with many similar errors like the following:
```
Uncaught (in promise) ReferenceError: setImmediate is not defined
    at RPCMultiplexer.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCMultiplexer.send (rpc-protocol.ts:230)
    at rpc-protocol.ts:134
    at <anonymous>
```

### Reproduction Steps
Start electron version of Theia with a hosted plugin. See debug console for errors.

**Comment by benoitf** [comment]
https://github.com/electron/electron/issues/2984 (settimeout)
