### ISSUE TITLE
Feature Request: Elegant Solution for Maven settings.xml Needed

### ISSUE THREAD

**Issue by brostbeef** [eclipse-che/che#9775]
### Description
In looking to use Eclipse Che in our organization, I have come across the following issue: There's no easy/good way to bring in the settings.xml file for our projects. Reason being: We have an internal artifactory repository that I need to utilize.

What I've thought of:
- Add settings.xml to the project repo...  (According to Maven documentation, this is a "no no" as it should not be project specific.  Makes sense as this would be our use case as well.)
- Add a volume mount... (Doable.  However, user credentials also go into the settings.xml file, so having a "common" settings.xml file shared between developers is not a good solution)

What I think should happen:
- Have a way to create the settings.xml file in the user directory as part of the setup.  Kinda like picking a "java + mysql" stack, could also have a "internal maven repo" stack that allows for settings.xml customization during the machine setup.

With the above said... I don't know how to set this up, so if the feature already exists, I'm sorry I didn't figure it out.

**Comment by eivantsov** [comment]
@brostbeef 

> Add a volume mount... (Doable. However, user credentials also go into the settings.xml file, so having a "common" settings.xml file shared between developers is not a good solution)


Why will this settings.xml be shared?

**Comment by brostbeef** [comment]
I'm looking at it from the perspective of a factory where I can generate a link to create the environment.  If I create a single mount for all machines to use, it will be shared.  Unless there is a way to customize the mount during creation?

**Comment by eivantsov** [comment]
@brostbeef your Factory may add a volume for `~/.m2`. Each developer will have to copy settings.xml to template that you put into your custom image, insert credentials and save. Next time a workspace starts, settings.xml along with a local maven repo will be persisted.

**Comment by brostbeef** [comment]
Finally got it to work.  (Wasn't able to get back to this until recently)  Thank you!
