### ISSUE TITLE
Go language server: wrong file name in editor tab

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9784]
LS used: https://github.com/theia-ide/go-language-server

F4 - go to definition works fine for packages inside the project. For external dependencies, relevant files are opened, however, editor tab shows file name from which this navigation was initiated:

![image](https://user-images.githubusercontent.com/5337267/40428708-8ef22a80-5ea9-11e8-8fb5-e964a9d57976.png)

**Comment by eivantsov** [comment]
Closing as cannot reproduce. Most certainly the two files had identical names which created confusion.
