### ISSUE TITLE
[Language server] clangd completion is too slow

### ISSUE THREAD

**Issue by claam** [eclipse-che/che#9786]
I used successfully Java and Python intellisense, that are really fast.
However, with clangd, it takes at least 5 seconds to get the result, for a basic function (both in C/C++).

I doesn't get error messages in logs.

Any one encountered the same issue ?

Edit
More informations about ma config:
- OS: Ubuntu 16.04
- Arch: AMD 64 bits
- Proc: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
- Browser: both Firefox and Chrome

Thanks

**Comment by musienko-maxim** [comment]
I may suppose that the problem may be around producing too long output in the dev-machine console:
![screencast-che-eclipse-che 172 19 20 240 nip io-2018 06 04-15-54-41](https://user-images.githubusercontent.com/1640058/40918963-aea35a00-6810-11e8-93c2-27b314894b7f.gif)

**Comment by claam** [comment]
Yes, that's the problem

**Comment by eivantsov** [comment]
@claam @musienko-maxim i'll try to play with clangd start command to make it less verbose to see if it fixes the issue.
