### ISSUE TITLE
Encrypted communication from browser to Eclipse Che running on docker with HTTPS, WSS protocol

### ISSUE THREAD

**Issue by ShagunBhatt** [eclipse-che/che#9788]
### Description
  From security perspective, we are thinking to encrypt all the communication when accessing to Eclipse Che from browser.
  We are using Docker as an Infrastructure of Eclipse Che.
  (OpenShift, Kubernetes are not used)

  We have checked the below Pull Request, but as it has been stagnating for about a month, could you please provide a workaround if any?
  “HTTPS using docker infrastructure”
     https://github.com/eclipse/che/pull/9097

**OS and version:**    
Eclipse Che : 6.0.0  with CHE_MULTIUSER=true 

Kindly reply on how above requirement can be achieved.

**Comment by eivantsov** [comment]
@ShagunBhatt this PR is the only community initiative available at the moment.

**Comment by ShagunBhatt** [comment]
@eivantsov Can any guide be provided for this PR ?

**Comment by eivantsov** [comment]
https://github.com/eclipse/che-docs/pull/393

**Comment by eivantsov** [comment]
@ShagunBhatt you may build Che from the branch in the PR and give it a try

**Comment by ShagunBhatt** [comment]
@eivantsov I have referenced the Che source from below : 
https://github.com/eclipse/che.git

There is no branch for #9097 . Please suggest a way to take the source code of this PR or i have to add changes manually to my eclipse che source version i.e. 6.0.0.

**Comment by eivantsov** [comment]
This PR is made from a fork. Take a look at PR description - github says it all

**Comment by ShagunBhatt** [comment]
@eivantsov For the Pull Request of #9097, could you please let us know a plan etc., if available, as by when it will be incorporated in the Release Version of Che? 
We are waiting for its support.

**Comment by eivantsov** [comment]
@ShagunBhatt some changes were requested from PR author. So, waiting for the PR to be finalized.

**Comment by ShagunBhatt** [comment]
@eivantsov Thanks for the information. is there any specific timeline ?

**Comment by eivantsov** [comment]
@ShagunBhatt I'd answer if I were the author of this PR. @hkolvenbach may know
