### ISSUE TITLE
Error while creating the project  Internal Server Error

### ISSUE THREAD

**Issue by kushalmokashi** [eclipse-che/che#979]
Hi,

System description:

Host OS: Windows
Virtual box:Oracle VM virtual box 5.0.12
guest OS: Ubuntu 14.04 trusty.
kernel version: 4.2.0-27-generic

Scenario:
1. I have a host system running a windows OS. I have installed the Oracle VM Vitrual box.
2. In this VM box I installed a ubuntu OS as VM. Installed Java 8.
3. After doing this I did setup the docker inside this ubuntu as per this link "https://docs.docker.com /engine/installation/linux/ubuntulinux/".
4. Downloaded the Eclipse Che from the this('https://www.eclipse.org/che/download/')link.
5. I opened that link and cliced on the "Download unsigned latest release from Codenvy servers  (142 MB)" hyperlink to download the zip file of che.
6. Extracted the eclipse-che-4.0.1.zip. And opened a command shell ran the bin/che.sh
7. Opened the mozilla firefox browser and went to this link "http://localhost:8080/dashboard".

Now when I click on New Project,I am getting the "Error while creating the project
Internal Server Error: fatal: unable to access 'https://github.com/che-samples/console-java-simple.git/': Could not resolve host: github.com " error.

The workspace will be created but not able to create the project.

All the log files have been attached and also a screen shot has been attached.

Is there any steps which I am missing during the setup.?
Please help to resolve this issue.

[1.txt](https://github.com/eclipse/che/files/206429/1.txt)
[catalina-0log.txt](https://github.com/eclipse/che/files/206432/catalina-0log.txt)
[localhost-access-0log.txt](https://github.com/eclipse/che/files/206430/localhost-access-0log.txt)
[machineIdlogs.txt](https://github.com/eclipse/che/files/206431/machineIdlogs.txt)
![screenshot from 2016-04-06 14 43 58](https://cloud.githubusercontent.com/assets/12235349/14317258/bd5625e0-fc07-11e5-9616-466e887beda8.png)

**Comment by ddementieva** [comment]
It seems there is no network in the container. Can you please try to run the image with bash using such command as `docker run -ti codenvy/ubuntu_jdk8 bash` and ping github.com manually?

**Comment by kushalmokashi** [comment]
@ddementieva I tried to ping the github manually inside the container. 
I got the output as  'ping: unknown host github.com' . 
I guess you are right there is no network in the container.
 It would be great if you help me to solve this issue.

**Comment by ghost** [comment]
I'd first make sure that Windows firewall isn't blocking anything in the VM.

Running `service docker restart` also never hurts.

**Comment by kushalmokashi** [comment]
@eivantsov I am able to ping the github from ubuntu VM's terminal.
So I don't think windows firewall is blocking this thing in the VM.
Executing docker ps in the terminal gives me the following output
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS                                                                                                                                                                         NAMES
c7f978d8f307        eclipse-che/che_workspacec81l9sj980xfmlm5_ws-machine_39j3v   "/bin/sh -c 'sudo /us"   25 minutes ago      Up 25 minutes       0.0.0.0:32788->22/tcp, 0.0.0.0:32787->4401/tcp, 0.0.0.0:32786->4403/tcp, 0.0.0.0:32785->4411/tcp, 0.0.0.0:32784->8000/tcp, 0.0.0.0:32783->8080/tcp, 0.0.0.0:32782->9876/tcp   che_workspacec81l9sj980xfmlm5_ws-machine_39j3v

**Comment by ghost** [comment]
You may want to try disabling iptables in the VM

**Comment by kushalmokashi** [comment]
@eivantsov I did runt he following commands in the VM terminal to disable the iptables.
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -F
Still the same behaviour.

**Comment by ghost** [comment]
What happens if you run:

`docker run -ti --net=host codenvy/ubuntu_jdk8 bash`
`curl -v github.com`

`--net=host` is the key here

**Comment by kushalmokashi** [comment]
@eivantsov I ran the commands as said by you. Below is the output

kumo@kumo-VirtualBox:~$ docker run -ti --net=host codenvy/ubuntu_jdk8 bash
user@kumo-VirtualBox:/$ curl -v github.com
- Rebuilt URL to: github.com/
- Hostname was NOT found in DNS cache
-   Trying 192.30.252.122...
- Connected to github.com (192.30.252.122) port 80 (#0)
  > GET / HTTP/1.1
  > User-Agent: curl/7.35.0
  > Host: github.com
  > Accept: _/_
  > 
  < HTTP/1.1 301 Moved Permanently
  < Content-length: 0
  < Location: https://github.com/
  < Connection: close
  < 
- Closing connection 0
  user@kumo-VirtualBox:/$

When you say "--net=host is the key here" that means I should replace the host by the IP address of the VM?

**Comment by ghost** [comment]
@kushalmokashi `--net-host` is a flag for Docker daemon to use host network. For some reason, docker network cannot get access to your Windows network that is connected to the internet.

**Comment by kushalmokashi** [comment]
@eivantsov  Hi, I am still not able to resolve this issue. I know its something related to the network configuration, but if somebody can help me to solve this then it will be of great help. Let me know what all details(like system configuration and docker configuration etc.) you need from my side.

**Comment by ghost** [comment]
@kushalmokashi I suggest that you start a thread with Docker community - this way you will resolve the issue much faster. I personally haven't met such a problem since my only Docker on Windows experience is running Docker in a VM created by docker-machine.

**Comment by kushalmokashi** [comment]
@eivantsov The issue is resolved for me. I had to explicitly configure the --dns="IP_Addr" in the docker file, which is located in the /etc/default/ folder. Now it works.
You can close the issue. Thanks for your time and the help.
