### ISSUE TITLE
cursor jump at external editing

### ISSUE THREAD

**Issue by Flax163** [eclipse-che/che#9790]
### Description 
if edit file, not through editor, cursor jumping.

**Reproduction steps**

1) Create project
2) Create text file
3) add git for project and commit text file
4) editing text file
5) revert using "git checkout ." 

**OS and version:**    
Che: 5.19
Chrome: 66
OS: Windows 7

**Diagnostics:** 
![jump_cursor_che_5_19](https://user-images.githubusercontent.com/8758749/40473210-9ab415ce-5f4c-11e8-9710-bb262f029789.gif)

on https://codenvy.io
![jump_cursor](https://user-images.githubusercontent.com/8758749/40473379-0c580762-5f4d-11e8-86e4-f5f4483a7434.gif)

**Comment by eivantsov** [comment]
@Flax163 Can you reproduce it with Eclipse Che?

**Comment by eivantsov** [comment]
Closed due to inactivity.
