### ISSUE TITLE
Display the build and revision on the dashboard

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#9791]
### Description
* Right now, to know the information of the build and revision, an user needs to create a workspace and open it in the IDE, after that open the 'About'.
* It is а bit uncomfortable and take some time.
* Would be nice to display the information about build and revision on the dashboard.

**Comment by Ohrimenko1988** [comment]
In my opinion, it should be displayed on demand. For example in "Diagnostic" section.

**Comment by gorkem** [comment]
+1 for putting this sort of info into diagnostics.

**Comment by gorkem** [comment]
@eivantsov Do you know if diagnostics view is used by users often?

**Comment by eivantsov** [comment]
@gorkem can't say it's a very popular feature but it's being used from time to time to discover any networking issues with Che. However, it is often more difficult to figure out why diagnostics failed than to find out reasons of failing workspaces.

**Comment by nickboldt** [comment]
Meanwhile, in CRW... https://issues.jboss.org/browse/CRW-168 thanks to a sed hack [1], we have all the version info you could possibly want in the dashboard.

[1] https://github.com/redhat-developer/codeready-workspaces/blob/6.19.x/Jenkinsfile#L175

Of course this would be way easier (and less dirty) if there was a way to pass this information to Maven at build time.

**Comment by sleshchenko** [comment]
> Display the build and revision on the dashboard 
> 
> > Right now, to know the information of the build and revision, an user needs to create a workspace and open it in the IDE, after that open the 'About'.

It's quite old issue, so I suppose at that time version of Dashboard and GWT IDE could be the same.
So, now if a user wants to know Che Server version + Dashboard version - we could provide it, but if Theia IDE version is needed - that a user must create a workspace and check the About Dialog there.

> +1 for putting this sort of info into diagnostics.

Seems the diagnostics page is removed.
Maybe we could add About dialog for Dashboard as well, which user could reach from here:
![Screenshot_20200327_123311](https://user-images.githubusercontent.com/5887312/77747380-43b21080-7027-11ea-8eb5-ef46289ac524.png)
Snapshot build could have the detailed version directly in the bottom, but not sure that it should be there for releases versions
