### ISSUE TITLE
Remove current analytics mecanism

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#9792]
### Description
Che integrates a basic analytics mechanism which log during how long a workspace was running. 
For compliance to the GDPR and the upcoming work on telemetry https://github.com/eclipse/che/issues/5483, we want to remove this mechanism.

**Comment by riuvshin** [comment]
@slemeur does that means you expect bugfix release once it is done? or it can wait for upcomming release next week

**Comment by slemeur** [comment]
We should be doing a bugfix release.

**Comment by riuvshin** [comment]
ok
