### ISSUE TITLE
Can eclipse che be used as a code editor inside JavaScript

### ISSUE THREAD

**Issue by prateekkohli2112** [eclipse-che/che#9798]
Hi,

I am trying to integrate a Java code editor like Ace/Code Mirror into my Javascript file inside a div HTML tag.

Is is possible to use eclipse che as a Java code editor in my JS file and integrate it inside a div element just like Code Mirror or ace.

I want to open a Java editor when a user clicks on a button.

Can we use eclipse che for this purpose.

Regards,
Prateek Kohli

**Comment by eivantsov** [comment]
@prateekkohli2112 you can open the IDE in an iframe. In fact, this is how it currently works - the IDE is an iframe in User Dashboard.

**Comment by skabashnyuk** [comment]
Closing. @prateekkohli2112 feel free to reopen this issue if you think it's still relevant.
