### ISSUE TITLE
How to create specific workspace per user (che multi-user)

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#9802]
Hi all,
    I installed eclipse-che multi-user using Docker and my che is installed inside `/usr/bmap/che/`. I noticed that workspaces are created inside in `/usr/bmap/che/instance/data/workspaces`. Is it possible for each user on our linux system and who have account on che, for example tkosted and edup to have their workspace created inside 
`/usr/bmap/che/instance/data/workspaces/tkosted/allOfWorkspaceIcreated` and `/usr/bmap/che/instance/data/workspaces/edup/allOfWorkspaceIcreated` and each user have access to his folder only ?

**Comment by eivantsov** [comment]
@KOSSOKO no, workspaces aren't sorted by usernames

**Comment by KOSSOKO** [comment]
@eivantsov thanks for the answer.

**Comment by KOSSOKO** [comment]
@eivantsov thanks a lot
