### ISSUE TITLE
Show List of Breakpoints

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9809]
Make a UI that can show a list of breakpoints. For starters, showing line breakpoints should be enough. Start with a fixed list of breakpoints for testing.

**Comment by tsmaeder** [comment]
@tolusha ?

**Comment by tolusha** [comment]
![screenshot from 2018-05-29 09-49-08](https://user-images.githubusercontent.com/1640675/40642367-99008e2e-6325-11e8-8a35-284a834d7b68.png)
