### ISSUE TITLE
Headless workspaces

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#9813]
Our team uses a [tool](https://github.com/outeredge/che-sync) we wrote to allow remote development on Che workspaces using, effectively SSH.

My question is, is it possible to disable the ws-agent or somehow limit it until the user explicitly connects to the IDE? We are finding a big resource drain on the server is the agent processes.

**Comment by eivantsov** [comment]
@davidwindell you can disable ws-agent for a workspace, however, in this case the IDE is unusable. 

There's no mechanism to start it on demand.

What do you mean by 

> the user explicitly connects to the IDE?

Opens it in a browser?

**Comment by davidwindell** [comment]
@eivantsov thanks, so I think what we will do here then is turn off the ws-agent and exec agent by default and they can be selectively enabled if anyone needs to use the IDE.

Yes, by explicitly connect I meant in the browser.

**Comment by davidwindell** [comment]
Just tested and without `ws-agent`, the projects don't seem to exist anymore in /projects (I can't get my head around why that would happen if /projects is mounted in)

**Comment by eivantsov** [comment]
@davidwindell that's interesting. Will check and get back with findings.

**Comment by gorkem** [comment]
@skabashnyuk how does this work with new IDE? Are we still running wsagent on those workspaces?

**Comment by sleshchenko** [comment]
@davidwindell I think it's because `projects` volume is automatically bound only to machine with `ws-agent`. But you can mount it manually, so just add `projects` volume to machine configuration, here is an example:
```WorkspaceConfig
{
  "environments": {
    "default": {
      "machines": {
        "my-machine": {
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          }
        },
        "installers": [],
        "servers": {
          "tomcat8": {
            "port": "8080",
            "protocol": "http"
          }
        },
        "recipe": {
          "content": "eclipse/ubuntu_jdk8",
          "type": "dockerimage"
        }
      }
    }
  },
  "name": "default",
  "defaultEnv": "default",
  "description": null,
  "commands": []
}
```

**Comment by sleshchenko** [comment]
@gorkem No, there are not running wsagent in new IDE workspaces. Theia just declares [projects volume](https://github.com/eclipse/che/blob/master/ide/che-core-ide-stacks/src/main/resources/stacks.json#L26-L29)

**Comment by davidwindell** [comment]
This is very helpful, thank you!
