### ISSUE TITLE
NTH: Add option to run selenium tests with maven profiles (currently only possible through the script)

### ISSUE THREAD

**Issue by ScrewTSW** [eclipse-che/che#9815]
### This issue is just NiceToHave concept.

For easier use of the upstream selenium tests, it would be really nice if we had an option to use maven profiles instead of the included scripts (discussed with @riuvshin and was deemed completely feasible to have maven-pure tests)

**Comment by riuvshin** [comment]
@vkuznyetsov ping

**Comment by dmytro-ndp** [comment]
@ScrewTSW: you can run selenium tests now by using maven if you set all required environment variables and maven parameters explicitly.
Or you meant another use case?

**Comment by ScrewTSW** [comment]
Well, it is possible to run them by setting appropriate values, but that's heavily IDE dependent.
Having those pre-set in maven profiles so that all we would have to do is call `mvn clean install <goal>` would be really beneficial for test execution (especially on ci.centos.org).
I would like to avoid scripts as much as possible, though I didn't say we have to drop the support for current scripts in use, just adding an option to use maven profile instead.

**Comment by rhopp** [comment]
Obsolete. Closing.
