### ISSUE TITLE
Update Documentation on SSH

### ISSUE THREAD

**Issue by mechevarria** [eclipse-che/che#9823]
### Description

It would be great if the instructions for SSH into a workspace were updated with examples on the Che website [SSH | Eclipse Che](https://www.eclipse.org/che/docs/chedir-ssh.html)

Is che-dir the right tool for getting into a workspace? I couldn't find a clear example and ended up doing a bunch of cli commands until I got something working.  I eventually used the `get-ssh-data` command, but that command output gave me a user of **root** that did not work.  I changed the user to **user** and I was able to get into the workspace.  

Maybe its just me, but I found it very confusing to figure out how to ssh into a workspace

![screenshot from 2018-05-25 11-02-18](https://user-images.githubusercontent.com/2657771/40551973-6511c586-600c-11e8-8b72-4106000b9ce7.png)

**Comment by eivantsov** [comment]
@mechevarria perhaps this doc is clearer https://www.eclipse.org/che/docs/docker-cli.html

**Comment by dmg3** [comment]
@mechevarria I'm having the same issue/error message shown here when I try to sync or ssh into a workspace.  Did you ever find a resolution to this issue?  I'm on ubuntu 14.04 LTS and che 6.19.0 
The command I run to sync is: 
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/asg/chedata:/data -v /home/asg/chetest:/sync eclipse/che:6.19.0 sync wksp-z0t4
