### ISSUE TITLE
[Request] How to start server in the same port (Wordpress bug)

### ISSUE THREAD

**Issue by thenets** [eclipse-che/che#9824]
### Description
I'm trying to use Eclipse Che to develop themes and plugins for Wordpress.
 The problem is: I need a fixed URL (domain + port) to access my Wordpress website.

Each time that I restart the Workspace a new port is redefined, so my Wordpress URL needs to be changed too.

I had the same problem with other application like Ghost CMS. Those applications need an absolute path.

### Reproduction Steps

- Create the Workspace
- Setup the Wordpress Installation
- Restart the Workspace
- Servers ports are automatically redefined
- Wordpress doesn't work anymore

Eclipse Che 6.5.0

**Comment by eivantsov** [comment]
@thenets There's single port policy for Che on Docker https://www.eclipse.org/che/docs/docker-config.html#single-port-policy 

This feature is also supported out of the box if Che is deployed to an OpenShift cluster.

**Comment by thenets** [comment]
@eivantsov Thanks a lot!! 😄 
This feature is very obscure to me. Maybe can be a good idea highlight this information in the documentation.

This is the command that I used:
```bash
docker run --cpus=".7" -it --rm -e CHE_SINGLE_PORT=true -e CHE_HOST=my.domain.com -v /var/run/docker.sock:/var/run/docker.sock -v /che:/data eclipse/che start
```

Thanks once again! ^^
