### ISSUE TITLE
Deploying with helm chart to minicube: how to get access

### ISSUE THREAD

**Issue by kostiamol** [eclipse-che/che#9832]
I've followed the [doc](https://github.com/eclipse/che/tree/master/deploy/kubernetes/helm/che) for deploying che. The command bellow was executed:
` sudo helm upgrade --install my-che --namespace che-ns --set global.ingressDomain=che ./`
Output:
![image](https://user-images.githubusercontent.com/5477699/40615091-ac79f13e-6285-11e8-825d-7eb04fc8309f.png)
But how could I get an access to the deployed che using the addresses below?
Master:` https://che-<che-namespace>.domain`
Workspaces servers: `https://server-host.domain`

**Comment by eivantsov** [comment]
@kostiamol `global.ingressDomain` should be a valid DNS or IP + wildcard dns like nip.io

If you deploy locally, it should be `${LOCAL_IP}.nip.io`

**Comment by kostiamol** [comment]
@eivantsov I tried: 
![image](https://user-images.githubusercontent.com/5477699/40666241-88c04c2c-635f-11e8-9cee-e29dc61a61d5.png)

The output of the command `sudo kubectl describe ing -n che-ns` is below (maybe it'll help):
![image](https://user-images.githubusercontent.com/5477699/40666141-534737cc-635f-11e8-9776-171f3e8a5e44.png)

**Comment by eivantsov** [comment]
Che should be available at `che-che-ns.135.238.177.27.nip.io`

**Comment by kostiamol** [comment]
@eivantsov It still doesn't work ;(

![image](https://user-images.githubusercontent.com/5477699/40708561-0a3fffe2-63f4-11e8-9478-365dff0b2ae1.png)

**Comment by eivantsov** [comment]
@kostiamol is this still an issue?
