### ISSUE TITLE
Introduce Output channel API

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9836]
The new plugin model should contain API for accessing the output channel. The task includes following items to be done:
- [x] define the API of the output channel interactions
- [x] document the API
- [x] develop the defined API
- [x] test it on the sample plugin

_Output channel - the place, where some logs, information, statuses could be provided by plugins and displayed._

**Comment by svenefftinge** [comment]
This issue should be tracked in Theia, no?
