### ISSUE TITLE
Introduce Plugin API for workspace folders

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9839]
The new plugin model should contain API for accessing the list of opened workspace folders and updating them. The task includes following items to be done:
- [ ] define the API of the workspace folders
- [ ]  document the API
- [ ]  develop the defined API
- [ ]  test it on the sample plugin

**Comment by vitaliy-guliy** [comment]
Pull request to upstream
https://github.com/theia-ide/theia/pull/2141
