### ISSUE TITLE
Introduce new namespace for current environment in Plugins API

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9845]
The new plugin model should contain API for accessing the information about current environment, where Theia IDE was run. The task includes following items to be done:
- [x] define the API for retrieving the following information:
     - [x] the environment variables
     - [x] query parameters as part of the url
- [x] document the API
- [x] develop the defined API
- [x] test it on the sample plugin

**Comment by mmorhun** [comment]
I think we shouldn't implementation of this issue with security issues about environment variables. So for now I just reuse what we have.

**Comment by mmorhun** [comment]
Sample plugin is added as part of https://github.com/theia-demo-plugins/theia-frontend-plugin/pull/8
