### ISSUE TITLE
Build of E2E testing jobs had failed on Eclipse Che CI because of existed github identity provider

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9846]
### Description
We encountered a number of builds failure on Eclipse Che CI because of the same error:
https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/293/consoleText
https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/294/consoleText
https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/229/consoleText
```
[INFO]: Che successfully deployed and is available at http://che-eclipse-che.172.30.3.252.nip.io 
Logging into http://localhost:8080/auth as user admin of realm master
Identity Provider github already exists
Build step 'Execute shell' marked build as failure
```

**Comment by dmytro-ndp** [comment]
List of [identity providers is empty at the moment](https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/299/consoleText):
```
Check if there is something remained after run...
Logging into http://localhost:8080/auth as user admin of realm master
[ ]
```

**Comment by riuvshin** [comment]
I do not see that issue anymore on latest builds 308-314
https://ci.codenvycorp.com/view/pr-builds/job/che-pullrequests-test-ocp/

So I consider it is fixed. Feel free to reopen if that will appear again.
