### ISSUE TITLE
Make it possible to use Theia's terminal widget for displaying Che Task's output

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#9847]
We need some widget to display a Che Task's output in Theia - see https://github.com/eclipse/che/issues/8974. Theia's terminal widget could be used for that but it requires some changes to be able to work with a terminal process running not only on the Theia backend.
So the goal of this task is to make the Theia's TerminalWidget configurable to be able to point it out to the terminal process launched on any endpoint.

**Comment by gorkem** [comment]
@vparfonov Is this on the next sprint?

**Comment by vparfonov** [comment]
@gorkem yes

**Comment by azatsarynnyy** [comment]
The issue has been solved by making the Theia's terminal widget more extendable (actually by changing the visibility of several internal fields) and using an extended version of that widget with an overridden mechanism of connecting to the terminal server.
