### ISSUE TITLE
Workspace management dashboard  work with custom OIDC working in query mode

### ISSUE THREAD

**Issue by i300543** [eclipse-che/che#9859]
### Description
We at SAP are trying to use latest che attached to our custom OpenIdConnect provider (we use cloud foundry xsuaa service)
our oidc .well-known/openid-configuration can be seen here :
https://research2.authentication.eu10.hana.ondemand.com/.well-known/openid-configuration

Our oidc emits and validates JWTokens, but does not support "preferred_username" claim, required by the che wsmaster.
to circumvent this problem i have made a pull request : 
https://github.com/eclipse/che/pull/9826
which fixes this issue, but still the workspace management UI does not manage to load with our custom OIDC provider. (wsmaster api's are working as expected with the JWT generated by it)

After short investigation, it looks to me that our OIDC does not support 'fragment' parameters mode in authorization grant flow, which is the default set here : 
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/keycloak/OIDCKeycloak.js#L105
and instead uses 'query' mode.
So i changed the mode while debugging to query, and then encountered the next problem: 
when fetching the token from the OIDC : 
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/keycloak/OIDCKeycloak.js#L439-L465
 (see attached request https://research2.authentication.eu10.hana.ondemand.com/oauth/token in the HAR file) 
In the network, request looks like it succeeds with 200 response, and tokens returned, but, in debug in line 441 req.readyState is 4, but req.status is 0 (not 200).
I suspect that this is happening because of the cross origin request ( when keycloak is used, it's host is the same as the wsmaster dashboard host, so there is no cross origin, but when custom OIDC is used, hostname is different, so different rules apply ?)

Also, our OIDC returns this header:
**Access-Control-Allow-Origin** : http://che-eclipse-sergey.eclipse-sergey.ingress.che-ci.devx-che.shoot.canary.k8s-hana.ondemand.com
, which allows browser access to the cross origin host, but does **not** return  the header:
**Access-Control-Allow-Credentials** :
while Keycloak does return it, with the value true.

I do not think i can change the headers returned by the OIDC provider, is there anything i can do to make the dashboard work for us ?

Sorry about so much text.

### Reproduction Steps
- checkout my PR: https://github.com/eclipse/che/pull/9826
- build che wsmaster + bake image + publish the image in docker image repo
- deploy to kubernetes cluster with this command (run from folder deploy/kubernetes/helm/che):
helm upgrade --install eclipse-sergey --namespace eclipse-sergey --set 'global.ingressDomain=eclipse-sergey.ingress.<kubernetes.cluster.suffix>,global.multiuser=true,global.serverStrategy=single-host,cheImage=\<image:tag\>,global.cheDedicatedKeycloak=false,customOidcProvider=https://research2.authentication.eu10.hana.ondemand.com ,cheKeycloakClientId=\<clientId\>' .

To get clientId and clientSecret contact me via mail, or just use any OIDC with query mode, deployed on different host than wsmaster itself. I think this issue will reproduce for any.

**Diagnostics:** 
attached the HAR file from recorded network
[workspaceDashboardStartup.zip](https://github.com/eclipse/che/files/2052627/workspaceDashboardStartup.zip)

**Comment by gorkem** [comment]
copying @davidfestal

**Comment by eivantsov** [comment]
@i300543 is this still an issue for you?

**Comment by i300543** [comment]
This is still an issue for us, because if custom OIDC provider is used, and the provider does not support 'fragment' parameters mode in authorization grant flow,
or does not return
'Access-Control-Allow-Credentials' : true 
header,
the che workspace management UI does not work (with multiuser)

Im not sure how much of a priority it is for you guys to support this kind of use-case.
we are using standart CF uaa service as oidc provider, but have no way to configure the things i mentioned

**Comment by z0r0** [comment]
Bumping this, as it's an issue for us too.
