### ISSUE TITLE
Investigate Mozilla Addons Server repository

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#9863]
Possibly we can use this for building our Market Place for Che Plugins 

- http://addons-server.readthedocs.io/en/latest/index.html
- https://github.com/mozilla/fireplace
https://github.com/mozilla/addons-frontend

**Comment by benoitf** [comment]
I'm adding link to marketplace doc (upper level than backend and frontend)
https://marketplace.readthedocs.io/en/latest/index.html

**Comment by benoitf** [comment]
it seems now the addon server include as well the UI (this is why fireplace is read-only)

**Comment by gorkem** [comment]
Please keep in mind that we want to able to run the marketplace optionally on-prem therefore day 1 and day 2 operations is my main concern with this.
