### ISSUE TITLE
Plugin Marketplace UI - Phase 1

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#9866]
### Description
The goal of this issue is to setup the initial UI to allow a user to browse a list of plugins and see details about a particular plugin. 

### List of plugins
![chemarketplace-browse](https://user-images.githubusercontent.com/1636769/40713575-94f01db4-6400-11e8-8fa7-7b40613eec45.png)

Note: In this initial phase the search and filters capabilities are not required

### Plugin details
![chemarketplace-plugin details](https://user-images.githubusercontent.com/1636769/40713580-996a828a-6400-11e8-9001-005ee6a54a5b.png)

### Plugin Metadatas
A plugin is defined by:

**Package binary**:
- `.che` (or .`cfa`) with everything necessary to “install” the plugin in Che 
- Container definition 
- UI webpack 
- User Documentation 

The package binary could also be a plain Theia extension.

**Primary Metadatas**: 
- Unique identifier 
- Title
- Author 
- Icon 
- Summary
- Version 
- Compatibility information

**Secondary Metadatas**:
- Category
- (optional) Tags
- (optional) Project details
  - Repository URL
  - Link to homepage
  - Link to changelog
  - Link to issue tracker
  - Link to license
  - Link to user documentation

**Overview Page**:
Defined in asciidoc

**Screenshots**:
Collection of images which can be displayed in the plugin's detail page

**Comment by vparfonov** [comment]
@slemeur can we close it?
