### ISSUE TITLE
Study Mozilla Firefox Marketplace frontend

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#9867]
### Description
Along with the work on https://github.com/eclipse/che/issues/9866 we should be studying what open source component for market place already exist.

The [Firefox marketplace](https://marketplace-frontend.readthedocs.io/en/latest/) seems an interesting candidate, as well as the server backend https://github.com/eclipse/che/issues/9863.

**Comment by gorkem** [comment]
looks like a duppo https://github.com/eclipse/che/issues/9863
