### ISSUE TITLE
Initial Plugin registry

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#9868]
### Description
In order to allow the work of other teams on the plugin model, we should be setting up an initial plugin registry which could be use to host the different plugins and serve them when a workspace is getting initialiazed.

At this moment, what's required would only be the ability to:
- host plugins (the `.cfa` which should probably better be named `.che`)
- an api to retrieve the list of plugins with their ID and URL
- should also allow plain Theia extensions

**Comment by skabashnyuk** [comment]
How these plugins are connected with Phase 1 of Workspace.Next implementation https://github.com/eclipse/che/issues/9406? How they are related to Services, Features.

Are this is all about standalone Theia and has no relation to Che or containers?

**Comment by benoitf** [comment]
hello, quick question @skabashnyuk 
```
"parameters": [
            {
              "name": "THEIA_PLUGINS",
              "value": "eclipse-che-ssh-extension.tar.gz"
            }
          ]
```

```
"parameters": [
            {
              "name": "THEIA_PLUGINS",
              "value": "che-theia-github.tar.gz"
            }
```


how do we download these .tar.gz file ?

**Comment by benoitf** [comment]
also, how do I upload pure theia plugins ? (no che feature archive) as marketplace should be able to handle both

**Comment by slemeur** [comment]
@skabashnyuk : If you can manage to provide the URL to download the plugins that would allow other team to move forward.

**Comment by benoitf** [comment]
@skabashnyuk 
I can describe the usecases if it may help

1. : Deploy "on the fly" a Che plugin from the registry from a running che instance.
 note: this che plugin has no workspace configuration (like a LSP to declare, etc) so there is no requirement to "stop/update workspace-config/start" a workspace
details:
      -  allow to list plugins from the IDE itself (or UD) and be able to install/uninstall plugins.
       --> Theia IDE can interact with registry, list and install plugins that are not impacting workspace configuration
It requires to get URLs of each .theia plugin (or external links) embedded in the original `che feature archive` 

2. Boot a workspace with a specified set of che plugins
In the workspace configuration, THEIA_PLUGINS env var is provided, with the URLs to grab the .theia files.
--> Theia, on startup, will analyze THEIA_PLUGINS, download the specified `.theia files` or external links/ids (if not already in a local cache for example)  and install them when booting the IDE

3. Deploy a `.theia` file plugin from a running instance of Theia.
allow to filter the type of plugins to only see `theia`plugins

**Comment by skabashnyuk** [comment]
@benoitf here https://github.com/eclipse/che/issues/9895#issuecomment-393506109 I've tried to adjust my vision to your thoughts.
