### ISSUE TITLE
Load Theia in Workspace.Next workspaces

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#9870]
### Description
PR https://github.com/eclipse/che/pull/9774 brings an ability to try Workspace.Next in action. But workspaces with Theia feature don't load Theia IDE on start. We need to figure out how to change workspace loader component to allow it open Theia IDE if there is a runtime server corresponding to it. 
FYI, for now, workspace loader seeks for Theia server in workspace configuration only. 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by skabashnyuk** [comment]
@garagatyi 
> But workspaces with Theia feature don't load Theia IDE on start.
Any ideas why?

**Comment by garagatyi** [comment]
Because workspace loader app scans workspace config for Theia server. And we don't have it in workspace next. Instead, we will have that server in runtime field but not on the very start of a workspace.

**Comment by l0rd** [comment]
@ashumilova are you going to work on that issue during current sprint?

**Comment by ashumilova** [comment]
@l0rd yes, it's in progress, facing some environment issues - but doable.
