### ISSUE TITLE
Create test user in Eclipse Che on OCP which is run remotely

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#9878]
### Description
E2E selenium tests of _Eclipse Che Multiuser on OCP_ are using keycloak admin CLI client inbuilt into local keycloak container as part of Eclipse Che multiuser to create test users. But we disallow creation of test user in case of we are testing product which is run remotely.

**_Solution_**: we can run docker container with keycloak admin CLI client locally and then use _--server_ parameter to create test user remotely.

**Comment by eivantsov** [comment]
@dmytro-ndp there's a simpler way. Since you already have a container with Keycloak CLI running remotely, you can use `oc exec` to execute such commands. Btw, it can well be the default method of creating a user and doing any Keycloak config/admin work.

**Comment by dmytro-ndp** [comment]
Thank you for advice, Eugene. It would simplify creation of test user beside we will need to download "oc" client somewhere locally and call it anyway.

**Comment by eivantsov** [comment]
@dmytro-ndp yes, that's my point - to deploy Che on OpenShift `oc` is must have anyway, so I think it's worth looking into doing remote execs rather than starting the same env locally.

**Comment by dmytro-ndp** [comment]
@eivantsov: could you, please, explain where we can obtain name of pod with keycloak (like **keycloak-1-ww7gk** from your example above) if Che is deployed remotely?

**Comment by eivantsov** [comment]
@dmytro-ndp you can grep it in the output of `oc get pods` (worst case) or you can use selector when getting pods. Just an example (you may find own ways of obtaining Keycloak pod name):

```
KEYCLOAK_POD=$(oc get pod --namespace=eclipse-che -l app=keycloak --no-headers | awk '{print $1}')
KEYCLOAK_ADM_SCRIPT="/opt/jboss/keycloak/bin/kcadm.sh"
COMMAND="create"
OPTIONS="identity-provider/instances -r che -s alias=github -s providerId=github -s enabled=true -s storeToken=true -s addReadTokenRoleOnCreate=true -s 'config.useJwksUrl="true"' -s config.clientId=************** -s config.clientSecret=************ -s 'config.defaultScope="repo,user,write:public_key"' --no-config --server http://localhost:8080/auth --user admin --password admin --realm master"
oc exec "${KEYCLOAK_POD}" -- "${KEYCLOAK_ADM_SCRIPT}" "${COMMAND}" "${OPTIONS}"

**Comment by dmytro-ndp** [comment]
Thank you for answer, @eivantsov 
Another moment: I have receive an error when try to execute the command against locally installed OCP origin:
```
Logging into https://172.19.20.137:8443/auth as user admin of realm master
Failed to send request - sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

AFAIK it's because I didn't define https cerificate to request to https://172.19.20.137:8443, is it?

**Comment by eivantsov** [comment]
@dmytro-ndp why are you using WebConsole endpoint instead of a local Keycloak? Take a look at the example above - I am using localhost:8080 which is where Keycloak is running in the container.

**Comment by dmytro-ndp** [comment]
The point is to create test user in Eclipse Che on OCP which is run **remotely** compare to selenium tests

**Comment by eivantsov** [comment]
@dmytro-ndp why do you need this `https://172.19.20.137:8443/`?

Can you share command you execute?

**Comment by dmytro-ndp** [comment]
My fault - you are right that we should use http://localhost:8080 when requesting keycloak pod.
I confused it with OCP console address which we should connect to firstly to obtain the keycloak pod name.
