### ISSUE TITLE
Add factory support for pulling from k8s YAML in repo

### ISSUE THREAD

**Issue by bmicklea** [eclipse-che/che#9879]
### Description
Today we allow factories to optionally [read runtime configuration from a dockerfile located in the repo](https://www.eclipse.org/che/docs/creating-factories.html#customizing-url-factories). However, this only works with dockerfiles today.

We should offer a similar ability to have factories read the runtime configuration from a Kubernetes YAML in a repo when using Che on Kube or OpenShift.

**Comment by bmicklea** [comment]
@benoitf your input here would be appreciated.

**Comment by slemeur** [comment]
This is aligned with the requirements from workspace.next https://github.com/eclipse/che/issues/8265
