### ISSUE TITLE
Fail to execute "mvn clean install" in che

### ISSUE THREAD

**Issue by gdjinjiahao** [eclipse-che/che#9882]
### Description
 

I clone the source code of che in [https://github.com/eclipse/che](url) to my local host(windows 7), then I run the cmmand "mvn clean install". But there are some exceptions in go-agents. The exception information is following:
> **[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (b
> uild-go-sources) on project go-agents: Command execution failed.: Process exited
>  with an error: 2 (Exit value: 2) -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
> rg.codehaus.mojo:exec-maven-plugin:1.6.0:exec (build-go-sources) on project go-a
> gents: Command execution failed.**
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:213)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:154)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:146)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
> LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
> LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreaded
> Builder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleSt
> arter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.jav
> a:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessor
> Impl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:498)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launche
> r.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:2
> 29)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launc
> her.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356
> )
> **Caused by: org.apache.maven.plugin.MojoExecutionException: Command execution fai
> led.**
>     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:326)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBui
> ldPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:208)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:154)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:146)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
> LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
> LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreaded
> Builder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleSt
> arter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.jav
> a:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessor
> Impl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:498)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launche
> r.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:2
> 29)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launc
> her.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356
> )
> **Caused by: org.apache.commons.exec.ExecuteException: Process exited with an erro
> r: 2 (Exit value: 2)**
>     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.
> java:404)
>     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166
> )
>     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
>     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
>     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBui
> ldPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:208)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:154)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.ja
> va:146)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
> LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (
> LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreaded
> Builder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleSt
> arter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.jav
> a:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessor
> Impl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:498)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launche
> r.java:289)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:2
> 29)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launc
> her.java:415)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356
> )
> [ERROR]
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please rea
> d the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
> xception
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> 
> [ERROR]   mvn <goals> -rf :go-agents

I run the maven as administrator and my golang is 1.10

**Comment by eivantsov** [comment]
@gdjinjiahao there should be the actual reason in logs just above the `[ERROR].` Have you got `GOROOT` and `GOPATH` in your env?

**Comment by gdjinjiahao** [comment]
@eivantsov yes,I check the environment variables, then the `GOROOT` and `GOPATH` is set correctly

**Comment by eivantsov** [comment]
@gdjinjiahao I think go agents cannot be compiled on Windows - that's why I asked for an error message preceding the final [ERROR].

**Comment by gdjinjiahao** [comment]
I find the error message preceding the final [ERROR]
```
[INFO] --- exec-maven-plugin:1.6.0:exec (build-go-sources) @ go-agents ---
# github.com/eclipse/che/agents/go-agents/core/process
core\process\process.go:311:9: undefined: syscall.Kill
# github.com/eclipse/che-lib/pty
..\..\..\che-lib\pty\ioctl.go:6:28: not enough arguments in call to syscall.Syscall
..\..\..\che-lib\pty\ioctl.go:6:29: undefined: syscall.SYS_IOCTL
..\..\..\che-lib\pty\run.go:21:46: unknown field 'Setctty' in struct literal of type syscall.SysProcAttr
..\..\..\che-lib\pty\run.go:21:60: unknown field 'Setsid' in struct literal of type syscall.SysProcAttr
..\..\..\che-lib\pty\util.go:18:9: undefined: setsize
..\..\..\che-lib\pty\util.go:29:32: not enough arguments in call to syscall.Syscall
..\..\..\che-lib\pty\util.go:30:3: undefined: syscall.SYS_IOCTL
..\..\..\che-lib\pty\util.go:32:3: undefined: syscall.TIOCGWINSZ
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```
So, the absence of `syscall.Kill` leads to this exception?

**Comment by eivantsov** [comment]
@gdjinjiahao yes, go agents can be compiled on Linux only. You can use `eclipse/che-dev` image to do that
