### ISSUE TITLE
Automatic opening of a new tab with hosted instance on ocp ends up in service unavailable

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#9894]
### Description
When user wants to test a plugin under development the main IDE starts hosted instance and only then opens a new tab, but user sees 503 error page. Hosted instance is actually started but ocp route hasn't ready yet. So refresh of that 503 error page in a few seconds resolves the problem, but it is very uncomfortable for development.

### Reproduction Steps
Run Theia hosted instance on ocp, quite often the problem appears.
This problem is not reproducible without ocp.

**Comment by gorkem** [comment]
I see similar behavior with Spring boot preview URLs as well. @l0rd is there a route configuration we can try that would eliminate this delay on route recognizing the server?

**Comment by l0rd** [comment]
No we cannot control the delay. And in some installations (with multiple sync'ed haproxy) it may last more than others. The correct approach should be to wait for the route to be available before opening the new tab.

**Comment by benoitf** [comment]
fixed in 6.13.0
