### ISSUE TITLE
Provide better error message, when git push fails

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#9898]
### Description
Right now, when git push fails, only general message is displayed:
![image](https://user-images.githubusercontent.com/1215011/40784433-f1910cf0-64e5-11e8-8a5e-f81ab01805a2.png)
This is completely misleading message in some cases (for example the case from `Reproduction Steps` section)
It would be great, if the message would tell what the actual error is (`rejected - non-fast-forward` for example)
For comparison, this is what eclipse shows to the user, when trying to push  to remote repository, where there is some commit, which hasn't been fetched:
![image](https://user-images.githubusercontent.com/1215011/40786774-2a75ca8c-64ec-11e8-9b85-91bd2f0e008a.png)

### Reproduction Steps
1) Have workspace running with cloned repository.
2) From some other place make a commit (C in the picture) and push it to remote branch.
3) Make a commit inside che workspace (D in the picture).
This is how it should look like right now:
![image](https://user-images.githubusercontent.com/1215011/40787020-da0a6764-64ec-11e8-812f-5b8233a8d19f.png)

4) Try to push that branch - This should not work - git rejects this push, as there are changes upstream, which are not in your local repository.
5) Message explaining what happened should appear. But instead of this, just general message is shown.

**OS and version:**    
RH-Che 6.4.1. on Openshift.io

**Diagnostics:**

**Comment by rhopp** [comment]
@dmytro-ndp I can see nothing suspicious in `/workspace_logs/ws-agent/logs/catalina.log` (nor in archives)

**Comment by eivantsov** [comment]
Hm... I have the following message in UI

```
failed to push 'master -> master' to 'git@github.com:eivantsov/php.git'. Try to merge remote changes using pull, and then push again.

```

**Comment by rhopp** [comment]
@eivantsov You have that message in Che in OSIO? This might be related to the way, how authorization against github works on OSIO (github token is injected by che-stareter using this endpoint: https://github.com/eclipse/che/blob/master/multiuser/keycloak/che-multiuser-keycloak-token-provider/src/main/java/org/eclipse/che/multiuser/keycloak/token/provider/contoller/TokenController.java#L51)

**Comment by eivantsov** [comment]
@rhopp this is upstream repo :) So, I used upstream Che to try to reproduce the issue you have run into.

**Comment by rhopp** [comment]
@eivantsov I'm aware this is upstream repo. The code is living hre (che-multiuser-keycloak-token-provider), so I reported it here.
I would try that directly on upstream che, but not sure how to run upstream che with this (the token injection) mechanism in place.
