### ISSUE TITLE
"Workspace is not running" pop-up window blocks workspace from being used

### ISSUE THREAD

**Issue by agajdosi** [eclipse-che/che#9900]
### Description
When user starts workspace from left menu bar, instead from pop-up window, the pop-up window gets stuck forever and in order to proceed, the page must be reloaded.

### Reproduction Steps
1. create a workspace
2. start workspace from left menu bar instead of pop-up window
![screenshot from 2018-05-31 17-10-10](https://user-images.githubusercontent.com/22000268/40790572-9cb48eea-64f5-11e8-9bb7-951b2e650ab5.png)

3. wait until the workspace is RUNNING (pop-up window does not dissapear)
![screenshot from 2018-05-31 17-12-11](https://user-images.githubusercontent.com/22000268/40790684-d597cc7c-64f5-11e8-9638-aa39b2c902f5.png)

4. pop-up cannot be closed, clicking on "start" gives error: Could not start workspace 'xyz' because its state is 'RUNNING'
![screenshot from 2018-05-31 16-58-00](https://user-images.githubusercontent.com/22000268/40790131-69553d5c-64f4-11e8-9d02-d170d0f916ef.png)

5. only way to get over it is to reload page or click to another workspace / menu item / etc

**OS and version:**
RHEL 7 through CDK (Minishift), using che addon for Che deployment
Eclipse Che: 6.5.2
Firefox 60.0 on Fedora

**Comment by eivantsov** [comment]
@agajdosi I just tried it on a local cluster, and starting a workspace the way you showed actually makes the popup disappear.  Can you consistently reproduce it?

**Comment by agajdosi** [comment]
Hi @eivantsov, thanks for trying. It is consistent for me, tried today 5 times with different workspaces and every time I face the issue.

**Comment by vparfonov** [comment]
@agajdosi Is this still actual for you? Looks like we can't reproduce it, maybe you have some additional information

**Comment by agajdosi** [comment]
@vparfonov No longer reproducible for me on Che 6.14.2.
