### ISSUE TITLE
Error: UPGRADE FAILED: error validating "": error validating data: found invalid field test for v1beta1.DeploymentSpec

### ISSUE THREAD

**Issue by xinjie188** [eclipse-che/che#9901]
### Description
Deploying with Helm
Multi User

### Reproduction Steps
Execute the command
helm upgrade --install <che-release-name> --namespace <che-namespace> -f ./values/multi-user.yaml --set global.ingressDomain=<domain> ./

Error message reported

Error: UPGRADE FAILED: apiVersion "rbac.authorization.k8s.io/v1" in che/charts/che-keycloak/templates/endpoints-monitor-role.yaml is not available

Let me change  rbac.authorization.k8s.io/v1 to  rbac.authorization.k8s.io/v1beta1 for endpoints-monitor-role.yaml

Execute the command
helm upgrade --install <che-release-name> --namespace <che-namespace> -f ./values/multi-user.yaml --set global.ingressDomain=<domain> ./

Error message reported：
Error: UPGRADE FAILED: error validating "": error validating data: found invalid field test for v1beta1.DeploymentSpec

**OS and version:**    
k8s version    1.6.11
eclipse che   6.7.0-SNAPSHOT
**Diagnostics:** 
No log information

Could it be that the k8s cluster version is low or the configuration file is not the latest cause？

**Comment by eivantsov** [comment]
@xinjie188 quite possible, since I cannot reproduce it on 1.9.0 cluster.

**Comment by xinjie188** [comment]
@eivantsov Thank you. I'll try a 1.9 cluster redeployment
