### ISSUE TITLE
Language Servers Providing providing Workspace Symbols should always be started

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9902]
Currently, language servers are only started when a relevant file is opened. However, when looking for workspace symbols, we should start the all activated language servers that could provide workspace symbols. Currently, no symbols will be found from LSs that are not started.
Note that starting language servers might be a performance hit. We should make sure work is not blocked while the language servers are started up.

**Comment by gazarenkov** [comment]
I would not say it can be qualified as a bug, LSP specs stated:

> Server lifetime
The current protocol specification defines that the lifetime of a server is managed by the client (e.g. a tool like VS Code or Emacs). It is up to the client to decide when to start (process-wise) and when to shutdown a server.

and I doubt we have something else specified.

Ideally, a client, caring of resources consuming, should start/stop LS on demand (which brings some complexity to impl of course but IMO is one of the ideas of LSP) and understand which LS(es) should be started. AFAIK file extension/name is used for this. 

Saying that I mean - we can choose one or another way or have both (with way to select), neither is bug but consciously choice.

**Comment by gorkem** [comment]
It should be possible for LS to opt-in to be started. For instance jdt.ls is started on vscode if it encounters a pom.xml or gradle file on the workspace. OTOH yaml LS is not started until a yaml file is opened on the editor and it does not make sense for it to be started.

**Comment by gazarenkov** [comment]
Yes, start of some LSes (such as Java) can be triggered by the opening project of particular type. 
For example we can expect Java (maven, gradle) project containing quite many .java files, so we can expect that *most probably* client will open java file (sooner or later) and so start java LS on opening such a project.

**Comment by eivantsov** [comment]
Just a side note: in case of an LS in a sidecar, it's started in the entrypoint/cmd of a container and since this is the main container process, failed LS == failed container, which means a failed workspace.

**Comment by gazarenkov** [comment]
@eivantsov 
Well, thats how it works but I would say it is not necessary to fail workspace for all the cases.
Like yaml LS's container failing may not be that important for starting workspace.

**Comment by gorkem** [comment]
I agree, we can still keep the container running despite of a LS start failure.
