### ISSUE TITLE
delete git project failed

### ISSUE THREAD

**Issue by paraseleneelf** [eclipse-che/che#9903]
Description
When I tried to delete a git project in che ,it failed. And then I found a strange file called ".nfs00000000032e015600000009e" in path ".git/object/pack".This file can not be deleted ,because device or resource busy.

Reproduction Steps
    1.import a project from git 
    2.delete the project
    3.delete project failed and that strange file appeared

OS and version:
    all image of che:6.4.0

**Comment by eivantsov** [comment]
@paraseleneelf what is your OS?

**Comment by paraseleneelf** [comment]
@eivantsov Ubuntu 16.04.4 LTS

**Comment by eivantsov** [comment]
@paraseleneelf is the local dir that you mount into `/data` an nfs volume?

**Comment by paraseleneelf** [comment]
@eivantsov this dir is not a n nfs volume,but the dir in environment variable called "CHE_PROJECTS_ROOT" is mount from an nfs volume

**Comment by eivantsov** [comment]
I think this is what causes the problem since workspace agent cannot delete this file. Not sure I understand what that file is.

**Comment by paraseleneelf** [comment]
I found a link “https://serverfault.com/questions/201294/nfsxxxx-files-appearing-what-are-those” explained where the file “.nfsxxxxxxx” from，but i don't know why the che process occupied the file ".git/object/pack/xxxxxx.pack". I'm sure no git command is running in the background.

**Comment by paraseleneelf** [comment]
@eivantsov I have tried many times and I found that If I called the API "/tree/{parent:.*}" with parameter "includeFiles=true" in ws-agent,the file ".git/object/pack/xxxxxx.pack" will be occupied.Can help me analyze what causes it?

**Comment by eivantsov** [comment]
@paraseleneelf is this still an issue for you?
