### ISSUE TITLE
Workspace can not be deleted after using not accessible image 

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#9905]
### Reproduction Steps
 - Go to dashboard and create the workspace by default "Java" stack
 - Go to workspaces list and click on created workspace
 - In the opened "workspace details" page go to a "Machine" section
 - Change machine image to "eclipse/ubuntu_jd"
 - Save changes and run workspace
 - After error message showing try to delete workspace
 - Pay attention to the error message

**Expected behavior:**
Workspace will be deleted

**Observed behavior:**
The error message is shown, the workspace is not deleted 

**Attachment:**
![screencast-che-eclipse-che 172 19 20 205 nip io-2018 06 01-11-16-51](https://user-images.githubusercontent.com/22724619/40832027-2b3ab976-6593-11e8-9a1f-10cecad7e629.gif)

**OS and version:**    
Che 6.7.0 ; Chrome 66.0 ; Fedora 28

**Comment by sleshchenko** [comment]
I think the reason for this issue is that Kubernetes/OpenShift runtime doesn't support start termination correctly. It should be fixed by https://github.com/eclipse/che/pull/9816

**Comment by sleshchenko** [comment]
Should be fixed by https://github.com/eclipse/che/commit/0b30ca1d9bf3a35b4997e1fac8004ac5a8fa5eea
