### ISSUE TITLE
Add new items to namespace for current environment in Plugins API

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9908]
The new plugin model should contain API for accessing the information about current environment, where Theia IDE was run. The task includes following items to be done:
- [ ] define the API for retrieving the following information:
     - [ ] appName (The application name of the editor, like 'VS Code', that runs the plugin
     - [ ] language (Represents the preferred user-language, like de-CH, fr, or en-US.)
     - [ ] machineId (A unique identifier for the computer.)
     - [ ] sessionId (A unique identifier for the current session. Changes each time the editor is started.)
     - [ ] appRoot (The application root folder from which the editor is running.)
- [ ] document the API
- [ ] develop the defined API
- [ ] test it on the sample plugin

**Comment by benoitf** [comment]
https://code.visualstudio.com/docs/extensionAPI/vscode-api#_env
