### ISSUE TITLE
Unexpected exceptions in dev console after enabling/disabling maven modules

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#9916]
### Reproduction Steps
*  Clone test project: [simple-maven-multimodule](https://github.com/maxura/CHE-maven-multimodule-sample.git)
* Configure as maven project and open parent `pom.xml`
* Exclude my-lib module

**OS and version:** 7885bc5f9b40926f

**Expected result:** the module should be excluded without errors.
**Actual result:** after excluding we have unexpected  errors on dev-machine console from xml parser:
![selection_004](https://user-images.githubusercontent.com/1640058/40846212-9f289064-65c1-11e8-8da9-4fb2e34e8059.png)
As is supposed it may influence on stability in the `CheckMavenPluginTest`.

**Comment by RomanNikitenko** [comment]
Fixed by https://github.com/eclipse/che/pull/10997
