### ISSUE TITLE
Some widget can not display normally

### ISSUE THREAD

**Issue by liubin10** [eclipse-che/che#9922]
Hi all

In Preferences and Create New Project dialog，some widgets can not display entirely.

![40902642-4519e134-6807-11e8-9bf3-b7c514a1bfd7](https://user-images.githubusercontent.com/32632875/41011099-c42792fc-696d-11e8-8bce-d23745006470.png)
![40902635-3fc134d0-6807-11e8-84ee-916e03493dbf](https://user-images.githubusercontent.com/32632875/41011100-c5737dd8-696d-11e8-8ed5-5c765eb7710c.jpg)

**Comment by liubin10** [comment]
@eivantsov No,it's in the common screen resolution,1920*1080.In the styles configurations  from Chrome debug, I didn't see any of word-wrap or width configuration. But if the host name is long enough, it'll be wrap. In some cases, it doesn't wrap.

**Comment by gazarenkov** [comment]
Kamino cloned this issue to [gazarenkov/che-ide6](https://github.com/gazarenkov/che-ide6/issues/8)
