### ISSUE TITLE
Che 6.3.0 does not show diagnostics after page refresh

### ISSUE THREAD

**Issue by philcolol** [eclipse-che/che#9923]
### Description
After refresh page diagnostics do not compute

![validations_test](https://user-images.githubusercontent.com/11789456/40903100-5324d79a-67e7-11e8-9d56-ab37557f83e1.gif)

### Reproduction Steps
1. Create any simple java project
2. Write some gibberish to produce validation errors
3. Refresh page
4. Diagnostics do not reappear, there is error message in dev-machine console related to websockets

This also reproduces with custom Language Servers.

**OS and version:**
Che 6.3.0; Chrome 66.0

**Diagnostics:** 
Log message in console:
```
2018/06/04 06:53:35 Failed to send websocket message: , due to occurred error websocket: close sent
2018/06/04 06:53:35 Error occurs on sending ping message to websocket. websocket: close sent
```

**Comment by RomanNikitenko** [comment]
Can not reproduce it for current 6.7.0 version. If I'm not mistaken it was fixed [here](https://github.com/eclipse/che/pull/9689)
