### ISSUE TITLE
Create sample plugin for demoing feature of workspace.next

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#9927]
The particular plugin is just an example of  the Theia plugin, that will be defined as part of workspace.next feature. It contains the registered action for Quick Open named "Launch Jenkins service" and the handler, that will call the service. _[TODO] - the details about service to be added_

**Comment by mmorhun** [comment]
[Here](https://github.com/mmorhun/workspace-next-demo-plugin) is the sample plugin.
