### ISSUE TITLE
Download URL of the Camel LSP server binary will soon be broken

### ISSUE THREAD

**Issue by lhein** [eclipse-che/che#9930]
### Description
We are cleaning up our tags and pre-releases for Camel LSP Server and therefore its very likely that the LSP will no longer be downloadable from the URL currently used in Che. I provided a PR with a 1.0.0 pre-release download url which is persistent and will not be deleted anytime soon. Please switch to that URL to ensure Camel LSP is still working in future.

### Reproduction Steps
not needed

**Comment by lhein** [comment]
see PR at #9928

**Comment by eivantsov** [comment]
Thanks @lhein merged
