### ISSUE TITLE
Che workspace does not start in kubernetes (nginx ingress not used as loadbalancer entry)

### ISSUE THREAD

**Issue by bs-matil** [eclipse-che/che#9936]
### Description

Hello, 
I run into an issue with che. If I deploy che the master just boots normal.

**The Setup** 

Che 6.6.0
Azure AKS 1.9.6

The master can be accessed at https://webide.ourdomain.com which works. 
I extracted the relvant endpoints from our config

```
  CHE_API: https://webide.ourdomain.com/api
  CHE_DEBUG_SERVER: "true"
  CHE_DOMAIN: webide.ourdomain.com
  CHE_HOST: webide.ourdomain.com
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: https://webide.ourdomain.com/agent-binaries/linux_amd64/bootstrapper/bootstrapper
```

**The Problem**

The workspaces cant be started correctly. 
* The ws container is created
* The ws ingress and service is created
* No issues show up anywhere

Anyways it fails.

**What happens while ws boot**
What happens is that the workspaces gets correctly started ->
* I checked the logs in the workspace container , both show now issues and just boot
    * bootstrapper  -> no issues in logs
    * ws-agent -> no issues in logs
     

Firefox never establishes a working websocket because che api reponse with:
`Server 'exec-agent/http' in machine 'dev-machine' not available.`

**LOGS**

**WS Master Logs**
```
2018-06-05 14:28:28,017[aceSharedPool-1]  [WARN ] [.i.k.KubernetesInternalRuntime 179]  - Failed to start Kubernetes runtime of workspace workspace14tkhghvpkq77i6u. Cause: Server 'exec-agent/http' in machine 'dev-machine' not available.
2018-06-05 14:28:29,115[aceSharedPool-1]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 375]   - Workspace 'test:wksp-9p1u' with id 'workspace14tkhghvpkq77i6u' start fai
```

**Access Logs : Workspace**
The ingress get created. I can call the url e.g.  https://webide.ourdomain.com/servero00uno55-dev-machine/server-4401/api from curl within the che master or outside with my browser both times I get 401 unauthorized which I guess is correct as i have no token attached to the requests. 
```
On the other hand I can see the following on the accesslog in the workspace container:
`10.244.3.6 - - [05/Jun/2018:13:48:43 +0000] "GET /server25ozgqg1-dev-machine/server-4401 HTTP/1.1" 401 1106           │che-workspaces   workspace14tkhghvpkq77i6u.dockerimage   0/1       Pending   0         0s
10.244.3.6 - - [05/Jun/2018:13:48:47 +0000] "GET /server25ozgqg1-dev-machine/server-4401/api HTTP/1.1" 401 1106       │che-workspaces   workspace14tkhghvpkq77i6u.dockerimage   0/1       ContainerCreating   0         0s
10.244.3.6 - - [05/Jun/2018:13:49:40 +0000] "GET /server25ozgqg1-dev-machine/server-4401/api HTTP/1.1" 401 1106
```

`

**Comment by bsukramlitt** [comment]
What really would help is to know where in the code i have to point my debugger to see how ws master establishes its connection to the workspace

**Comment by eivantsov** [comment]
@sleshchenko can you take a look please?

**Comment by sleshchenko** [comment]
> The ingress get created. I can call the url e.g. https://webide.ourdomain.com/servero00uno55-dev-machine/server-4401/api from curl within the che master or outside with my browser both times I get 401 unauthorized

4401 - is port of `wsagent` server. And logs contain information about `exec-agent/http`. Please make sure that it is accessible. The URL should be like the following `https://webide.ourdomain.com/servero00uno55-dev-machine/server-4412/process`

**Comment by eivantsov** [comment]
@sleshchenko in this case ws-agent ingress is just an example. Exec agent is just the first one to check I think. I think if ws agent is accessible, there shouldn't be any issues with exec agent for example.

**Comment by sleshchenko** [comment]
@eivantsov Then it can be a networking issue like firewall needs to be configured.
@bsukramlitt To debug it you can set a breakpoint at https://github.com/eclipse/che/blob/8f041d8db6d799e683c5c2f0c22190954b487773/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/ServersChecker.java#L202 and check servers checks URLs. If they are correct and the same are available from `curl` then you can check response code here https://github.com/eclipse/che/blob/602a77d4585e063b928dd154b14b763a706678be/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/HttpConnectionServerChecker.java#L66

**Comment by garagatyi** [comment]
BTW are HTTPS certificates self-signed? Is a provider of certificates a widespread one? 
I'm asking because when certificates are self-signed or provider is not well known Java might not be able to establish a connection without adding certificates to JRE.

**Comment by bsukramlitt** [comment]
@garagatyi  no we use a common public cert issuer. Its accepted by jvm and default linux distros.

**Comment by bsukramlitt** [comment]
@sleshchenko I'll check the breakpoints sson

**Comment by bsukramlitt** [comment]
okay this one is interesting

http://null/server3hlzxj14-dev-machine/server-4401/api/?token=machinexk27tofz3qbw5w4tm9f0nbbrqaoctc0j04ssin02134spav4gc3z4rk6yd5vdvisnwx0om9uoe0dyyoa6yfrpi4ggo0lnzycczzavm38935hwsg34r30tm438ncbw6ec

anyone sees the issue :D?
just kidding I'll look into it to see whats not initialized there

**Comment by sleshchenko** [comment]
Server host should be initialized here https://github.com/eclipse/che/blob/a48d4b42c88e79c23bb148ef3719a2c1e8be219c/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/KubernetesServerResolver.java#L100-L104

**Comment by bsukramlitt** [comment]
final String host =
        ingressRule.getHost() != null
            ? ingressRule.getHost()
            : ingress.getStatus().getLoadBalancer().getIngress().get(0).getIp()

**Comment by bsukramlitt** [comment]
actually all ingress which got created by che have no host configured. Can i set the Host somehow manually. Which it doesn't look like if I look at the code.

**Comment by garagatyi** [comment]
Oh. have you enabled ingress controller? It is part of kubernetes cluster, not Che. And without it Che can create ingresses but they don't work as expected.

**Comment by bsukramlitt** [comment]
@garagatyi 
The ingress works as expected. 
Che does create ingress entries for all workspaces. This entries are picket up by ngin and I get a route for all  workspaces servcies. 

The issue is caused by the way che creates the route internally. If che would just use the CHE_API host name or something like that it would just work.

**Comment by sleshchenko** [comment]
I think you should configure che_hos by configuring server_strategy https://github.com/eclipse/che/blob/ac3b4016492fcfb9361243bc708f1191d06c1adf/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L338-L342
More info about them are in `MultiHostIngressExternalServerExposer`, `SingleHostIngressExternalServerExposer`, `DefaultHostIngressExternalServerExposer` classes.

**Comment by bsukramlitt** [comment]
This is just a guess correct me if I'm wrong :) 
The Problem looks to me like that you made assumptions about the deployment. Which would mean that the nginx always is attached directly to the LB service and therefore gets an external ip. Which is not always the case for example not in our environment.

**Comment by sleshchenko** [comment]
@bsukramlitt 
> Which would mean that the nginx always is attached directly to the LB service and therefore gets an external ip. 

It's just default configuration, see my comment [above](https://github.com/eclipse/che/issues/9936#issuecomment-394974760).

**Comment by bsukramlitt** [comment]
https://github.com/eclipse/che/blob/602a77d4585e063b928dd154b14b763a706678be/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/hc/HttpConnectionServerChecker.java#L66
ServiceAccountsun.net.www.protocol.http.HttpURLConnection:http://serverbvnesgzs-dev-machine-server-4412.webide.ourdomain.com/process?token=abcd

**Comment by sleshchenko** [comment]
@bsukramlitt Take a look https://github.com/eclipse/che/blob/ac3b4016492fcfb9361243bc708f1191d06c1adf/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L461-L467 and https://github.com/eclipse/che/blob/a48d4b42c88e79c23bb148ef3719a2c1e8be219c/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/IngressTlsProvisioner.java#L42

**Comment by bsukramlitt** [comment]
@sleshchenko  but i dont wont to enable tls internally in the cluster. I have loadbalancer in front of the nginx ingress of che. Will this still work?

**Comment by sleshchenko** [comment]
@bsukramlitt Sorry, I afraid I don't know =)

**Comment by eivantsov** [comment]
@bsukramlitt I think this might be the case where Che server ingress is ok for ws agents but not vice versa. And Ingresses for agents are not OK for Che sever, and thus when trying to reach them, cert authority cannot be validated. Just an idea...I have seen a few cases like this on OpenShift infra.

**Comment by bsukramlitt** [comment]
The problem is that the ingress for the ws now get configured for e.g. serviceabcs.webide.mydomain.com
but the endpoint enforces https so che would have to use https://serviceabcs.webide.mydomain.com/some/api/endpoint. But it uses http and one can't change it

**Comment by eivantsov** [comment]
And che.infra.kubernetes.tls_enabled=true for you?

**Comment by bsukramlitt** [comment]
@eivantsov
I configured now 
```
CHE_INFRA_KUBERNETES_SERVER__STRATEGY: multi-host
CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: ourdomain.com
CHE_INFRA_KUBERNETES_TLS__ENABLED: true
```
Which results in the following url to reach the service.
 `sun.net.www.protocol.https.DelegateHttpsURLConnection:https://serverirr1k0zv-dev-machine-server-4412.ourdomain.com/process?token=eyJ....`

 Which can't work in our environment cause the url does not route to che as it would need the subdomain webide to router to che.

Yes I can change this to ' CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: webide.ourdomain.combute than the certificate Alternative Name *.ourdomain.com no longer fullfills the route whith 4 dots. 

I have the feeling I have to think about this and file a feature request. It seems like this can only work if I put the nginx ingress as entrypoint for the whole soluiton.

Thanks for your help anyways! 
Great community 👍

**Comment by bsukramlitt** [comment]
@eivantsov  please close
