### ISSUE TITLE
Import project name has a backslash

### ISSUE THREAD

**Issue by liyanliang1994** [eclipse-che/che#9944]
### Description
Import a project from github, and the project name has a backslash at the page of workspace.
### Reproduction Steps
![test](https://user-images.githubusercontent.com/39881038/40989559-c1fb32d8-6920-11e8-86e1-c73df66db0e1.gif)
**OS and version:**    
che 6.6.0
**Diagnostics:**

**Comment by liyanliang1994** [comment]
[326th line in ProjectImportManager.java](https://github.com/eclipse/che/blob/483f0492f856f43ebe4738e8b465e6a51a770a3c/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectImportManager.java#L326)
shoud be
`String name = wsPath.substring(wsPath.lastIndexOf(separator) + 1);`

**Comment by eivantsov** [comment]
@liyanliang1994 and it does not happen if you correctly finish import process, ie set a project type. So not sure this is a bug, unless @vparfonov claim it is.

**Comment by vparfonov** [comment]
Any way strange behavior i will take a look

**Comment by eivantsov** [comment]
Closed due to inactivity. @vparfonov may reopen with findings.
