### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by RickJWagner** [eclipse-che/che#9945]
https://www.eclipse.org/che/docs/openshift-multi-user.html contains these:
"Instructions to deploy Che to OSD are identical to those for OpenShift Container Platform."
"Instructions to deploy Che to OSO PRO are identical to those for OpenShift Container Platform."
In each case, the link to 'OpenShift Container Platform' is https://www.eclipse.org/che/docs/openshift-container-platform
The link above gets a 404 (Not Found).

**Comment by RickJWagner** [comment]
I see that the side of the page has a bullet list with a link "OpenShift Container Platform", this one is a link to https://www.eclipse.org/che/docs/openshift-multi-user.html#openshift-container-platform and it works.

**Comment by eivantsov** [comment]
@RickJWagner thanks - will be fixed asap
