### ISSUE TITLE
Unable to stop instance of hosted plugin on Ubuntu

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#9951]
### Description
 

Hosted plugin instance on Ubuntu/Linux mint doesn't want to be stopped.

### Reproduction Steps

To reproduce:
- start  instance of Theia with hosted plugin; new tab must be opened and Theia with hosted plugin is loaded;
- switch to the main Theia and stop instance of hosted plugin; the process of hosted Theia still stay running and corresponding browser tab can be refreshed

**OS and version:**    
Linux mint

**Comment by mmorhun** [comment]
Must admit, that on Fedora stop command works as expected (tested on 27 and 28).
