### ISSUE TITLE
Deploying in multi-user mode using helm chart: che & keycloak not initialized

### ISSUE THREAD

**Issue by kostiamol** [eclipse-che/che#9952]
I used the ommand:
`sudo helm upgrade --install eclipse-che --namespace che-ns -f ./values/multi-user.yaml --set global.ingressDomain=che ./`
I can't find any errors.

![image](https://user-images.githubusercontent.com/5477699/41035196-2fd32372-698c-11e8-8067-01726d07b222.png)

![image](https://user-images.githubusercontent.com/5477699/41035221-444edd28-698c-11e8-8c1f-b019bc10c52b.png)

![image](https://user-images.githubusercontent.com/5477699/41035254-5fd4c4ae-698c-11e8-88cd-66b9cb646d9b.png)

**Comment by eivantsov** [comment]
`global.ingressDomain=che` why che? 

You should get logs from keycloak container. Che cannot start because keycloak is not up.

**Comment by kostiamol** [comment]
@eivantsov What's the problem with `global.ingressDomain=che`? I thought that I can use whatever I want as a domain name. 

![image](https://user-images.githubusercontent.com/5477699/41043402-2718d9c6-69a4-11e8-8090-34cba4367319.png)

**Comment by eivantsov** [comment]
@kostiamol no, it has to be a valid DNS

As to Keycloak, you need to dig info on why Keycloak pod never gets to start. If I saw logs and Keycloak server fails, I could have helped. In this particular case, there's zero info on wht k8s fails to even start the pod.

**Comment by kostiamol** [comment]
@eivantsov The problem was that images used apk to download packages but I was behind the proxy so I added proxy as an env var. Keycloak, PostgreSQL work, but now Che is experiencing troubles. Che pod tried to pass the readiness and livenss probes but every time it failed. I commented that lines from deployment.yaml in order to view its logs. It's the exception:
```
2018-06-08 07:26:20,601[ost-startStop-1]  [ERROR] [o.a.c.c.C.[.[localhost].[/api] 4752] - 
Exception sending context initialized event to listener instance of class 
[org.eclipse.che.inject.CheBootstrap]
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Error injecting constructor, java.lang.RuntimeException: Exception while retrieving 
OpenId configuration from endpoint: 
http://keycloak-che-ns.che/auth/realms/che/.well-known/openid-configuration
...
Caused by: java.net.UnknownHostException: keycloak-che-ns.che
```

**Comment by eivantsov** [comment]
@kostiamol che is not a valid DNS, is it? When Che server tries to connect to keycloak it fails. Redeploy with either a valid DNS or `$IP.nip.io` as domain.

**Comment by kostiamol** [comment]
@eivantsov There are too many "che" words in config. Is there any particular place where I can put "nip.io" instead of "che"? Maybe it's `CHE_INFRA_KUBERNETES_INGRESS_DOMAIN` ?

**Comment by eivantsov** [comment]
```
--set global.ingressDomain=$IP.nip.io
```

**Comment by kostiamol** [comment]
@eivantsov I'm using private infrastructure in order to deploy che. Admin told me that I shouldn't use nip.io. So my deploy command is:
`sudo helm upgrade --install che --namespace che-ns -f ./values/multi-user.yaml --set global.ingressDomain=$IP --set isHostBased=false ./`

Che still can't see neither keycloak nor postgres. So I'd like to check them by myself. I've tried to find keycloak using the address` https://keycloak-che-ns.$IP` but it has failed.
Did a make a mistake somewhere?

**Comment by kostiamol** [comment]
The problem was in ingress controller.
