### ISSUE TITLE
adding sample plugin to che

### ISSUE THREAD

**Issue by rahul545** [eclipse-che/che#9955]
I tried adding che-plugin-menu to che. For this I made a change in the pom.xml inside the plugin folder present in the che source code. Then I copied che-plugin-menu in the plugin folder and built it. I cant see any changes. Do I need to makes changes somewhere else?

**Comment by eivantsov** [comment]
@rahul545 perhaps you need to start with https://www.eclipse.org/che/docs/framework-overview.html

**Comment by rahul545** [comment]
I built the che-plugin-menu using che-ide-server extension from samples. However when I use the che-ide-extension , I get an error even though the plugin only modifies the ide. What could be the reason?
