### ISSUE TITLE
Add options to generate different plugin samples in Theia plugin generator

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#9956]
### Description
For now when creating new Theia plugin user has choice between server and client plugin only. 
Last time it generated many lines of code which I just had to delete.
The goal of this issue is to add choice between sample plugins:
- empty plugin (just config with empty implementation)
- hello world plugin (implementation contains only hello world command)
- full API plugin (implementation use all possible method of API)

Note that in total here should be at least 6 templates (3 client side + 3 server side plugins).

**Comment by benoitf** [comment]
yes thx for this issue.

I would say that we could enable toggle on what we want to use in generated plugins
like
- commands
- information message
- quickopen
- statusbar

etc.

Or we may need to group some of them.

Also frontend and backend should use the same templates (no duplicating the code)

to conclude, the palette command should contain or needs to be organized in a way so it's easy to find which commands are available for this plugin.
Or we need to have a widget, or something else to see what is possible to do.
