### ISSUE TITLE
Wrong behavior the 'Save' button in the 'Preferences' 

### ISSUE THREAD

**Issue by artaleks9** [eclipse-che/che#9959]
**Reproduction Steps:**
* Open the IDE and click _Profile_ -> _Preferences_ -> _Contribute_ (as example)
* The _Save_ button is disabled
* Change the state of the checkbox (the _Save_ button becomes enabled)
* Click on the 'Refresh button

**Expected behavior:** 
* the _Save_ button should be disabled after click on the _Refresh_ button

**Observed behavior:**
* the state of the _Save_ button is not changed

**Che version**: 6.7.0
**OS and version:** Fedora 28
**Che install:** Docker/OCP
**Docker version:** 17.09
**API docker version:** 1.32

**Additional information:**
* Related selenium tests: _ContributeTabTest_
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:
![preferences-save-btn](https://user-images.githubusercontent.com/5408906/41107220-921ea31e-6a7a-11e8-8174-d6c2e3a3417d.gif)

**Comment by RomanNikitenko** [comment]
I can reproduce the same behavior for check boxes of Profile -> Preferences -> IDE -> General  and Profile -> Preferences -> IDE -> Welcome pages, but can not reproduce for check boxes of Profile -> Preferences -> IDE -> Editor page for example.
So I think we should test all pages of Preferences and identify trouble spots

**Comment by artaleks9** [comment]
Thanks a lot @RomanNikitenko
