### ISSUE TITLE
OpenShift: Cannot start workspaces if username/password is provided in Che deployment env

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#9961]
### Reproduction Steps

1. Deploy Che (single user is OK)
2. Configure `CHE_INFRA_KUBERNETES_USERNAME` and `CHE_INFRA_KUBERNETES_PASSWORD`
3. Create and start a workspace. 

If `CHE_INFRA_OPENSHIFT_PROJECT` is empty, the error is:

```
2018-06-07 18:39:28,860[default.svc/...]  [WARN ] [k.c.d.i.WatchConnectionManager 195]  - Exec Failure: HTTP 403, Status: 403 - serviceaccounts is forbidden: User "system:anonymous" cannot watch serviceaccounts in the namespace "workspaceeq39y3fi9pximakw": User "system:anonymous" cannot watch serviceaccounts in project "workspaceeq39y3fi9pximakw"
```

If `CHE_INFRA_OPENSHIFT_PROJECT` is the same namespace where Che is deployed, the error is different:

```
2018-06-07 18:49:45,241[default.svc/...]  [WARN ] [k.c.d.i.WatchConnectionManager 195]  - Exec Failure: HTTP 403, Status: 403 - events is forbidden: User "system:anonymous" cannot watch events in the namespace "eclipse-che": User "system:anonymous" cannot watch events in project "eclipse-che"
--
  | java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'

```

So, it looks like fabric8 client logic has changed: previously, if an invalid passwor dis provided, it fell back to service account, which in the latter case has access to namespace.

Using auth token works as expected.

Env used: a local Origin 3.9 - oc cluster up.
Che version: latest nightly
Cannot be reproduced with 6.6.0

**Comment by l0rd** [comment]
@eivantsov this new behavior makes more sense to me: if the admin provides a username and password to access the openshift API Che should use it and fail if the credentials do not have enough privileges. If the admin explicitly provides username and password we should never fall back to service account because Che was explicitly configured not to do so. And we should adapt the case of auth token to behave the same. WDYT?

**Comment by eivantsov** [comment]
@l0rd yes, I agree that if credentials are set we should fails with a clear error message in case of unauthorized.

But the issue has to be fixed anyway.

**Comment by l0rd** [comment]
@eivantsov yes I agree with you that we need to fix that. And what are the scenarios where the use of username/password/token is preferred to the use of a service account? I am wondering if the fix would not be to remove the support of username/password/token and only support using a service account.

**Comment by eivantsov** [comment]
With username and password fabric8 client can create resources outside Che namespace, ie namespace per workplace scenario, while Che SA has admin priviliges only in Che namespace. You can give Che SA admin privileges at a cluster scope of source.

**Comment by l0rd** [comment]
We had a short discussion this morning with @eivantsov and @sleshchenko about how to simplify Che configuration in an OpenShift deployment. What we have concluded is that we only need to support the following 2 scenarios:

#### 1. Workspaces and Che master are deployed in the same namespace

- Che SA is used to create workspaces
- Simplest configuration, good for try and play
- Has limitatiosn: users workspaces are not isolated and users cannot `oc rsh`
- That's the only option for Che single user
- That's the default configuration

#### 2. Workspaces are created in users namespaces ([che docs link](https://www.eclipse.org/che/docs/openshift-admin-guide.html#create-workspace-objects-in-personal-namespaces))

- Users tokens are used to create workspaces
- A distinct namespace is created for every workspace
- Multi tenant ready
- It is more complicated to setup (Keycloak should be setup to use OpenShift identity provider)
- If workspace idling is turned on Che SA should have cluster wide privileges to be able to idled workspaces in other namespaces
- Property `che.infra.openshift.oauth_identity_provider` need to be setup
- This config cannot be applied to a Che single user

As a consequence the following properties won't be needed anymore:

```properties
che.infra.kubernetes.username
che.infra.kubernetes.password
che.infra.kubernetes.oauth_token
che.infra.openshift.project # for option n.1 the k8s/openshift client will automatically use the namespace the Che SA belongs to)
che.infra.kubernetes.namespace
```

cc @garagatyi @davidfestal

**Comment by davidfestal** [comment]
@l0rd @eivantsov Just a point: the creation of workspace in user namespaces is an **Openshift-only** feature. This is not available for the kubernetes infrastructure, at least for now.

Is it expected that the Kubernetes infrastructure would therefore not support multi-user scenarios ?

**Comment by l0rd** [comment]
@davidfestal that's a good point but we can still use scenario n.1 (everything in one namespace) for multi-user k8s right? And open an issue to support scenario n.2 in k8s. What do you think? 

cc @guydaichs

**Comment by eivantsov** [comment]
@l0rd I never set any credentials when deploy multi user Che to MiniKube and Che creates a namespace per workspace.

**Comment by davidfestal** [comment]
@eivantsov @l0rd I was just meaning that, in the case of Kubernetes, scenario 2 would probably be:

- Users tokens are used to create workspaces
- A distinct namespace is created for every workspace
- Multi tenant ready
- Che SA should have cluster wide privileges to be able to create workspaces in other namespaces
- This config cannot be applied to a Che single user

This mainly means that `che.infra.openshift.oauth_identity_provider` wouldn't be setup, but the Che SA would have sufficient rights to create workspaces in new namespaces.

**Comment by sleshchenko** [comment]
Also, we missed and didn't discuss that n.2 scenario with configured `che.infra.openshift.project` may be useful too. It may be useful when a user doesn't have permissions to create new projects but has predefined one (like OSIO use case). This scenario may be used to limit user's resources but setting quotas for user's namespace/project by cluster admin.
@l0rd @eivantsov Do you think it could be useful or a distinct namespace for every workspace would be enough for now?

**Comment by l0rd** [comment]
@eivantsov so yes it already works on kubernetes. But anyway to be consistent on all infra, if Che SA is used, we should not create a namespace for workspace. As per [the definition of namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#when-to-use-multiple-namespaces] using a distinct one for eache workspace is overkill when using a unique service account. 

@sleshchenko I agree with you. I would consider that out of scope of **this** issue but definitely something we should consider in a second step.

**Comment by garagatyi** [comment]
@sleshchenko @l0rd isn't this use case already implemented? if so, should we consider to change the code to remove this ability and then fix it later?

**Comment by ibuziuk** [comment]
> As a consequence the following properties won't be needed anymore:
> 
> che.infra.kubernetes.username
> che.infra.kubernetes.password
> che.infra.kubernetes.oauth_token
> che.infra.openshift.project # for option n.1 the k8s/openshift client will automatically use the namespace the Che SA belongs to)
> che.infra.kubernetes.namespace
> 

@amisevsk @l0rd got a question regarding scenario about having che server & workspaces created in different (but fixed) namespaces for single-user che. Am I correct that this use-case is not going to be supported anymore ? 
As part of testing quotas / resource limits [1] I wanted che-server be in `mini-che` and workpspaces in `workspaces` namespace on minishift. I failed to configure it for `6.7.0` and switched back to `6.6.0` (once cm entries for username / password / project were updated I was able to test this scenario). 

[1] https://github.com/redhat-developer/rh-che/issues/675

**Comment by sleshchenko** [comment]
@ibuziuk As far as I remember we discussed it during our meeting and answer is It would be possible by using Che Service Account with cluster scope permissions. 
Only cluster admin is able to grant Che Service Account cluster scope permissions so comparing to the previous implementation it would not be possible to use such scenario by a normal user on a cluster. But it should be fine for testing purpose on minishift.

**Comment by eivantsov** [comment]
@sleshchenko @ibuziuk yes, this is what has been documented https://www.eclipse.org/che/docs/openshift-admin-guide.html#who-creates-workspace-objects. If a cluster admin grants che sa cluster scope privileges, we can keep using it with namespace per workspace strategy (everything belongs to one OpenShfit account).

**Comment by eivantsov** [comment]
@amisevsk I don't think having `che.infra.openshift.project` is awful. So, +1 to keep it as indeed efforts to get rid of it are not worth it, imho.

**Comment by amisevsk** [comment]
@eivantsov @garagatyi Sounds good. We can reassess if it becomes a problem further down the line but I agree here.

**Comment by amisevsk** [comment]
Fixed by https://github.com/eclipse/che/pull/10529
