### ISSUE TITLE
Workspace.next - CheService model adjustment

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#9964]
We knew that the phase 1 w.next model was not perfect and that some incremental updates would be needed. With that in mind we have identified [a flaw in current CheService implementation](https://github.com/eclipse/che/pull/9774#discussion_r192922360) and should be refactored. 

### Refactoring proposal

- Rename `CheService` as `DevTool`
- Rename `Container` as `CheContainer`
- Move `Servers` list from `Container` to `DevTool` and renamed it as `DevToolEndpoints` 
- Exposed port in a container should be represented as `CheContainerPort` and have a matching `DevToolEndpoint..targetPort`
- Collapse `CheServiceSpec` in `CheService`
- Add an `id` field for `DevTool` to be referenced in `CheFeature`

![Plantuml png](http://www.plantuml.com/plantuml/png/XLF1Yjj03BtFL-YyaEnz2M5BsMCXa2-GPxJnW6TaHd9eAFtt8dkodjg5taRIqvFq_FmkYaMdDBYCYMH4Jz3H9nU2Nyxv0KNWUqzNAlVeBGTmW4IA0HNdG4RoxlSUUnt9L_oTYaJEytlaeikZiBBdOGvGjSHkKf8vz9mLOwOY3VCpLqbZmXlDByhtsfKIvh1G21KRkypdOKhKS5sNOcMoowtMtCc7m_QKD-XHW3E1srHU3FpShk8IveTRamQfGrk0JLrrnq-b0gtibs6wnVmyEApRRbMb74QEMVVoxTW-AhGzVgQNozGDqS-1OhcHNhZezlFOngm4oYFmvuxMyD_MxDTY40NGUnA9tK3GFO2rfmA1xg3CWq3C4WE10z2UG30HZ1nULtacYVa6AD2pgANV7C2fEv--fXqjUpwSTaijXTDhTmP7EO1Tq0YpjPQX_--nrLTFNxToDwmcOsMcdoCB1SiOTjNfvR2NidLAYvoX_p8SWE5Qr-tsMC7rEwBCg_z0zNtCDmSVToeFqtMlec8rnQ8aIC_J421PBw3rRCSPi55yV-Bn-FVuDh3Ybj1-cNVAOKh37m00)

[Plantuml source](http://www.plantuml.com/plantuml/uml/XLF1Yjj03BtFL-YyaEnz2M5BsMCXa2-GPxJnW6TaHd9eAFtt8dkodjg5taRIqvFq_FmkYaMdDBYCYMH4Jz3H9nU2Nyxv0KNWUqzNAlVeBGTmW4IA0HNdG4RoxlSUUnt9L_oTYaJEytlaeikZiBBdOGvGjSHkKf8vz9mLOwOY3VCpLqbZmXlDByhtsfKIvh1G21KRkypdOKhKS5sNOcMoowtMtCc7m_QKD-XHW3E1srHU3FpShk8IveTRamQfGrk0JLrrnq-b0gtibs6wnVmyEApRRbMb74QEMVVoxTW-AhGzVgQNozGDqS-1OhcHNhZezlFOngm4oYFmvuxMyD_MxDTY40NGUnA9tK3GFO2rfmA1xg3CWq3C4WE10z2UG30HZ1nULtacYVa6AD2pgANV7C2fEv--fXqjUpwSTaijXTDhTmP7EO1Tq0YpjPQX_--nrLTFNxToDwmcOsMcdoCB1SiOTjNfvR2NidLAYvoX_p8SWE5Qr-tsMC7rEwBCg_z0zNtCDmSVToeFqtMlec8rnQ8aIC_J421PBw3rRCSPi55yV-Bn-FVuDh3Ybj1-cNVAOKh37m00)

**Comment by skabashnyuk** [comment]
@l0rd about ```Add an id field for DevTool to be referenced in CheFeature``` AFAIK we talk about using id in routes and service discovering techniques. For the referencing purposes, we are going to use name and version.

**Comment by l0rd** [comment]
@garagatyi I have updated the model to use the name `ChePlugin` instead of `DevTool`. We will need to introduce the `CheEditor` and to remove `CheFeature` from the model. But I think it's ok to postpone these 2 steps as part of the walking skelethon epic.

**Comment by garagatyi** [comment]
We decided to remove name field from CheContainer since it is not needed now. If we find that we need it we will be able to add it back.

**Comment by garagatyi** [comment]
@l0rd do we really want that ChePluginEndpoint contain field `isPublic` instead of `public`? I'm OK with that, just want to clarify

**Comment by benoitf** [comment]
I don't remember where I said it but I raised same issue, public is shorter (than isPublic)
