### ISSUE TITLE
Open Editor on Library Class Files in Theia

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#9972]
Currently, when we do a "go to definition" on a library file (let's say java.lang.Object), nothing happens. We would like to open the source for java.lang.Object in an editor. Java support (hover, etc.) should then be enabled in the class file.
There are a couple of things we need to do here:
1. Enable returning jdt:// urls from jdt.ls in the init options passed to the LS
2. Create a handler in Theia that can provide content for jdt:// urls
3. Extend language server configuration to bind jdt.ls to class files
4. Test LSP funtionality for class files: does stuff like call hierarchy, references, etc. work when invoked from or containing class files?

**Comment by JPinkney** [comment]
Out of curiosity I skimmed through this when looking at the external library issue and found that enabling classFileContentsSupport in the extendedInitializationOptions allows document outlining, go to definition, go to symbol to work in class files. However I was unable to get references to work. I'm not exactly sure where that issue lays. 

Also, I think 2 is already done with [this](https://github.com/theia-ide/theia/blob/master/packages/java/src/browser/java-resource.ts).

**Comment by JPinkney** [comment]
PR https://github.com/theia-ide/theia/pull/2199

**Comment by tsmaeder** [comment]
Seems refs in vscode don't work either, so for the purposes of this issue, it's fixed.
