### ISSUE TITLE
Make theia Docker image be able to use yarn cache on Openshift

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#9978]
### Description
Current Theia image when is started on Openshift can't use yarn cache folder from docker image build `/usr/local/share/.cache/yarn/v1`. Because of that usage of `THEIA_PLUGINS` env var in Theia container makes it fetch all the dependencies from scratch and workspace start fails because of timeout.
On Docker cache is used and start is fast enough. 
So, we need to fix it somehow. 
`yarn cache dir` returns this on Openshift:
```
/home/theia $ yarn cache dir
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000090000".
/tmp/.yarn-cache-1000090000/v1
/home/theia $
```

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@eivantsov It prevents us from being able to use Theia extensions on Openshift, so I will be very grateful if you know how to fix that sooner than later.

**Comment by benoitf** [comment]
this docker image https://hub.docker.com/r/wiptheia/wip/ includes all the stuff to handle openshift (and openshift.io)

**Comment by eivantsov** [comment]
@benoitf but you do not run theia build as you use this one for the new plugin model, correct?

**Comment by benoitf** [comment]
@eivantsov I used yarn inside, in order to create from scratch a plugin with a yeoman generator so I would say we're able download npm dependencies, etc. Before it was not possible due to "invalid permission" or 'directory not writeable' errors, etc.

**Comment by eivantsov** [comment]
@benoitf I only see these dirs writable for root group https://github.com/theia-demo-plugins/wiptheia-docker-image/blob/master/Dockerfile#L50

What is the secret then? 

With wiptheia you are not running yarn build against theia itself, right? Just building the plugin? Maybe I am missing smth, but looking at the Dockerfile does not give me a clear answer.

**Comment by benoitf** [comment]
https://github.com/theia-demo-plugins/wiptheia-docker-image/blob/master/Dockerfile#L23 ?

**Comment by eivantsov** [comment]
Well, that's user with id 1001 - it won't be writable unless you do what you do on line 50. Probably you do that to make jsons and js files have user permissions as they are probably ADDed with root ones.

Can you please clarify, if this image is used for Theia using the new plugin model, ie when Theia isn't rebuilt to include a new plugin?

**Comment by benoitf** [comment]
this image is used when using new plugin model but I don't see as well why it's not useable when using extensions as well.

Do you have a specific error with this image when using theia extensions ?

**Comment by garagatyi** [comment]
Since new plugin system is not yet in place I'm seeking for a way how to use the old extension one which recompiles Theia. 
In this particular case if yarn cache is not writeable then recompilation will take to much time and workspace won't start.

**Comment by benoitf** [comment]
@garagatyi AFAIK the new plugin system is in place. The API is limited (so you can not write so many nice plugin but system is there) but it can be tested, there are already published examples

**Comment by garagatyi** [comment]
OK, sorry, I wasn't aware that it is in place. 
But does that image fix described permissions issues?

**Comment by eivantsov** [comment]
@benoitf as @garagatyi said, in your case you do not build Theia, and thus never hit this case of building Theia from scratch.

**Comment by garagatyi** [comment]
Just to clarify this long discussion for others - I still think that this issue needs to be addressed and that image created by Floran with cool hosted plugin stuff doesn't solve this issue.

**Comment by benoitf** [comment]
@garagatyi issue is not because ssh extension is already installed in the image
https://github.com/theia-demo-plugins/wiptheia-docker-image/blob/master/Dockerfile#L36
?

**Comment by garagatyi** [comment]
I don't know. Maybe. But current nightly seems not containing this extension and fails because it builds Theia for too long. 
Do you think that removing that extension will help?

**Comment by benoitf** [comment]
I don't think so, if extension is already there, build is quite fast, dependencies being there

**Comment by eivantsov** [comment]
@benoitf do you use yarn cache to build Theia? Not a plugin but Theia itself? AFAIK, you do not. While in Alex's case Theia is rebuilt (existing extension model)

**Comment by benoitf** [comment]
@eivantsov yes I fully understand what @garagatyi is doing.

**Comment by mmorhun** [comment]
Fixed
