### ISSUE TITLE
Should Che on Openshift support Kubernetes recipes?

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#9979]
### Description
Currently, Che doesn't support k8s recipes on Openshift infra. And I thought it does. So, should we add support or not?

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by garagatyi** [comment]
@slemeur @gorkem @l0rd WDYT?

**Comment by gorkem** [comment]
It should support it.
Do you know the reason? k8s recipes should be a subset of OS,  is it some limitation that we are adding?

**Comment by slemeur** [comment]
Yes it is something that we should be supporting. The docs are also claiming that we support the k8s recipes (https://www.eclipse.org/che/docs/recipes.html#supported-recipe-formats) 

I assume we support it for K8S infra support and will be able to use it for OS infra.

**Comment by eivantsov** [comment]
@garagatyi what is k8s recipe?

If I take Kind: List with Kind: pod and Kind: service, it works on both infras for me

**Comment by garagatyi** [comment]
@eivantsov but only if you put correct type  - for OS infra type is openshift, for k8s infra type is kubernetes.

**Comment by eivantsov** [comment]
@garagatyi thanks. Yes, it feels weird to me now that if I have kubernetes recipe type we refuse to create a workspace even though the recipe itself is identical to OpenShift one.

**Comment by eivantsov** [comment]
To clarify a bit... the below recipe should be ok for OpenShift infra. Now, it's ok only if `"type": "openshift"`.

```
      "recipe": {
        "type": "kubernetes",
        "content": "apiVersion: v1\nkind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   labels:\n    app: microservice-app-example\n    service: auth-api\n   name: auth-api\n  spec:\n   containers:\n    - \n     env:\n      - \n       name: AUTH_API_PORT\n       value: '8081'\n      - \n       name: JWT_SECRET\n       value: myfancysecret\n      - \n       name: USERS_API_ADDRESS\n       value: 'http://users-api:8083'\n     image: eivantsov/auth-api\n     imagePullPolicy: Always\n     name: auth-api\n     ports:\n      - \n       containerPort: 8081\n     restartPolicy: Always\n     resources:\n      limits:\n       memory: 512Mi\n - \n  apiVersion: v1\n  kind: Service\n  metadata:\n   labels:\n    app: microservice-app-example\n   name: auth-api\n  spec:\n   ports:\n    - \n     port: 8081\n   selector:\n    service: auth-api\n - \n  apiVersion: v1\n",
        "contentType": "text/x-yaml"
      }
```

**Comment by l0rd** [comment]
K8s and Openshift resources `Pod` and `Service` are identical so that's a no brain. We already support them.

@garagatyi I thought your question was about the k8s resources that do exist or do not match OpenShift resources (i.e. ingresses or deployments). In this rare cases I think we should not bother: if ever we will support Kubernetes Ingress we should not support it in OpenShift. But as of today we only support `Pod` and `Service` so the problem doesn't exist.

**Comment by eivantsov** [comment]
@l0rd you're not the only one who through about objects themselves rather than type :)

I'd say that if now openshift and k8s recipes are identical it makes no sense not to support k8s type on openshift infra.

However, in future, if both infras support unique objects like ingresses or dpeloymentConfigs, it becomes quite tricky.

**Comment by garagatyi** [comment]
@eivantsov I agree that support of k8s Ingresses and Deployments in OS is tricky. Because of that if we add support of k8s recipe type now and remove it when we start supporting Ingresses on k8s infra then UX would be quite bad - user can create a workspace with his recipe on one Che instance which is running on kubernetes but can't move it to another Che instance which is running on OS. 
I think that Workspace.Next is supposed to use any supported recipe type and convert it to supported objects. So maybe we should delay this issue until we figure out how workspace next will address this?

**Comment by eivantsov** [comment]
@garagatyi @l0rd should this issue be converted into a task?
