### ISSUE TITLE
Implement showOpenDialog method for Theia plugin system

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#9986]
### Description
 
To have an ability to select a file in a plugin for Theia, need to implement `showOpenDialog` method from vscode interface: https://github.com/Microsoft/vscode/blob/0cdbe60ffa64639857a44a6717de23d202910bbb/src/vs/vscode.d.ts#L5877

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by evidolob** [comment]
VSCode docks: https://code.visualstudio.com/docs/extensionAPI/vscode-api#_window showOpenDialog

**Comment by vitaliy-guliy** [comment]
Issue on Theia repo https://github.com/theia-ide/theia/issues/2153
