### ISSUE TITLE
Fail to create pull request

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#9987]
### Description
Not able to create pull request.

### Reproduction Steps
1. Clone your github repository. Example: https://github.com/skabashnyuk/petclinic
2. Checkout to some branch. Example ```fix```
3. Commit some changes.
4. Try to create PR.
![pr_bug](https://user-images.githubusercontent.com/1614429/41217209-e0051508-6d5f-11e8-8dd7-0b7e915d77ad.png)

**Comment by skabashnyuk** [comment]
Couse of the issue is a fact that during panel initialization fired 4 PartStackStateChangedEvent simultaneously. Those 4 events generate 4 ```org.eclipse.che.plugin.pullrequest.client.workflow.Context``` with the wrong state inside because of this code from WorkflowExecutor class

```
  public void init(final VcsHostingService vcsHostingService, final ProjectConfig project) {
    final Optional<Context> contextOpt = getContext(project.getName());
    if (!contextOpt.isPresent()) {
      doInit(vcsHostingService, project);
    } else {
      checkVcsState(contextOpt.get())
          .then(
              new Operation<Boolean>() {
                @Override
                public void apply(Boolean stateChanged) throws OperationException {
                  if (stateChanged) {
                    invalidateContext(contextOpt.get().getProject());
                    doInit(vcsHostingService, project);
                  } else {
                    eventBus.fireEvent(new CurrentContextChangedEvent(contextOpt.get()));
                  }
                }
              });
    }
  }
```
are not expected to be running simultaneously.

**Comment by RomanNikitenko** [comment]
I reproduced the bug.
In my case I watch that SelectionChangedEvent is fired 4 times simultaneously.
![pullreq_bug](https://user-images.githubusercontent.com/5676062/41220721-f3d6f1a4-6d6a-11e8-89d4-041b0662376f.png)
