### ISSUE TITLE
[WIPTheia] Add support for preferences schema from contribution point of a manifest file

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#9990]
### Description

A plugin should be able to provide its own preferences schema. We should implement a mechanism which parses and respects the scheme provided by a plugin.

1. Describe the schema in json file
2. Point the file location in package.json [TODO define the configuration in package.json]
3. Plugin meta data handles the value in package json, proceses and passes along with other plugin metadata

**Comment by AndrienkoAleksandr** [comment]
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration

**Comment by AndrienkoAleksandr** [comment]
I'm going to PTO, so summary about current state:
Working branch: https://github.com/theia-ide/theia/tree/CHE-9990-2
Samples (in dirty development state): https://github.com/theia-demo-plugins/theia-frontend-plugin/tree/workspaceConfigSamples;
Done: parsed preference chema from plugin contribution point in the manifest file, created consolidated configuration for extensions and plugins based on extension pref chema and plugin pref chema. 
Remaining stuff: 
-  throw onConfigurationChangedEvent, 
- update configuration on uninstall extension,
- apply to the workspace configuration "user preferences",
- check synchronization for all pref events,
- apply more samples and clean up them.
During development created issue:
https://github.com/theia-ide/theia/issues/2339
https://github.com/theia-ide/theia/issues/2290
https://github.com/theia-ide/theia/issues/2289
