### ISSUE TITLE
Auto whitelist GIT SSH URLs

### ISSUE THREAD

**Issue by mathus13** [eclipse-che/che#9998]
It seems that less-standard git hosts, such as self hosted servers, need to be white listed.

I wish that this was a more automated process such that if a user adds a VCS url to a domain that is not recognized they could get a notice that it will be queued for validation. The user could then be notified when their VCS host is ready to be used by their codenvy workspaces.

**Comment by eivantsov** [comment]
@mathus13 this restriction is applied to codenvy.io only. It's not relevant for Che. You can open the similar issue in codenvy repo https;//github.com/codenvy/issues
